from wx.lib.embeddedimage import PyEmbeddedImage
#----------------------------------------------------------------------
Actor = PyEmbeddedImage(
    b'iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAQAAAC1+jfqAAAAOGVYSWZNTQAqAAAACAABh2kA'
    b'BAAAAAEAAAAaAAAAAAACoAIABAAAAAEAAAhWoAMABAAAAAEAAAhWAAAAAMFeALwAAAACYktH'
    b'RAD/h4/MvwAAAAd0SU1FB+oFEBQhNSLxkMcAAAAldEVYdGRhdGU6Y3JlYXRlADIwMjYtMDUt'
    b'MTVUMTg6NDU6MjYrMDA6MDANER8HAAAAJXRFWHRkYXRlOm1vZGlmeQAyMDI2LTA1LTE1VDE4'
    b'OjQ1OjI2KzAwOjAwfEynuwAAACh0RVh0ZGF0ZTp0aW1lc3RhbXAAMjAyNi0wNS0xNlQyMDoz'
    b'Mzo1MyswMDowMFgrh1oAAAASdEVYdGV4aWY6RXhpZk9mZnNldAAyNlMbomUAAAAZdEVYdGV4'
    b'aWY6UGl4ZWxYRGltZW5zaW9uADIxMzT4qaKHAAAAGXRFWHRleGlmOlBpeGVsWURpbWVuc2lv'
    b'bgAyMTM0QVJ5bwAAAD10RVh0aWNjOmNvcHlyaWdodABDb3B5cmlnaHQgMjAwNyBBcHBsZSBJ'
    b'bmMuLCBhbGwgcmlnaHRzIHJlc2VydmVkLp5m3CkAAAAjdEVYdGljYzpkZXNjcmlwdGlvbgBH'
    b'ZW5lcmljIFJHQiBQcm9maWxlGqc4jgAAAL1JREFUKM+FkU0KggAQhb/RkARb1Q08gzcIogME'
    b'4Q3qDkFBHsE6SrQVgu4RtQhqGUbhtPAvLfFt3zfzHjPQIgHYAWAwQgBlTwLAGDAysMcQWxFP'
    b'PAWbIQ7ZWL7JJ5i4ySYJpy4Bfu6UEX1ZPQdbB509rCtLbmnEVwe6smYOhLogrnQYp0CskVpq'
    b'aVTa0KHou0txxShGSqDQq36HKmByAMxmQLjnxZsipGrXgYQ3kt35L3DkDJyagQuXtu/+6AM3'
    b'FC6JM8nctgAAAABJRU5ErkJggg==')

#----------------------------------------------------------------------
Aggregation = PyEmbeddedImage(
    b'iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAQAAAC1+jfqAAAAAmJLR0QA/4ePzL8AAAAHdElN'
    b'RQfqBRAUITUi8ZDHAAAAJXRFWHRkYXRlOmNyZWF0ZQAyMDI2LTA1LTE2VDIwOjMzOjI0KzAw'
    b'OjAwsQEprgAAACV0RVh0ZGF0ZTptb2RpZnkAMjAyNi0wNS0xNlQyMDoyOTozMiswMDowMLmK'
    b'678AAAAodEVYdGRhdGU6dGltZXN0YW1wADIwMjYtMDUtMTZUMjA6MzM6NTMrMDA6MDBYK4da'
    b'AAAAi0lEQVQoz72QwRGCQAxFX3bAWeDM2IEdcLADqcEObYAy9EArjLpG4mVZBb140H9L/pvM'
    b'/4GfSwC6NLZvgIu24OZouhDtCuGM5pwWQBbtgFpR0ygfgIpAgHbYbvxeV894/nA9OsCmhdpo'
    b'CyEdCCU3FL8Ojd5nDcYUskS4oBn9C2AIkmqCgbD79lF/0AMXfTRUOGJ6fwAAAABJRU5ErkJg'
    b'gg==')

#----------------------------------------------------------------------
Association = PyEmbeddedImage(
    b'iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAQAAAC1+jfqAAAAAmJLR0QA/4ePzL8AAAAJcEhZ'
    b'cwAALiMAAC4jAXilP3YAAAAHdElNRQfqBRAUITUi8ZDHAAAAJXRFWHRkYXRlOmNyZWF0ZQAy'
    b'MDI2LTA1LTE2VDIwOjIwOjEyKzAwOjAwdud/tAAAACV0RVh0ZGF0ZTptb2RpZnkAMjAyNi0w'
    b'NS0xNVQxODo0NToyNiswMDowMHxMp7sAAAAodEVYdGRhdGU6dGltZXN0YW1wADIwMjYtMDUt'
    b'MTZUMjA6MzM6NTMrMDA6MDBYK4daAAAAMklEQVQoz2NgGAKAcQYBBUyETGBhYGAwZgjBIbua'
    b'4RwLAwPDf4b/+E04x3COAjcMCQAAfGkGRBO1OvEAAAAASUVORK5CYII=')

#----------------------------------------------------------------------
Class = PyEmbeddedImage(
    b'iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAQAAAC1+jfqAAAAAmJLR0QA/4ePzL8AAAAJcEhZ'
    b'cwAALiMAAC4jAXilP3YAAAAHdElNRQfqBRAUITa7+MF9AAAAJXRFWHRkYXRlOmNyZWF0ZQAy'
    b'MDI2LTA1LTE1VDE4OjQ1OjI2KzAwOjAwDREfBwAAACV0RVh0ZGF0ZTptb2RpZnkAMjAyNi0w'
    b'NS0xNVQxODo0NToyNiswMDowMHxMp7sAAAAodEVYdGRhdGU6dGltZXN0YW1wADIwMjYtMDUt'
    b'MTZUMjA6MzM6NTMrMDA6MDBYK4daAAABBklEQVQoz4WRv0rDUBSHv3sTmtooxT/YSTo5iDg6'
    b'6Uu42rnv4Ds4CT6A+ABSnERwq6/gEsRBdBA02rSBJM09DslN7tYzHQ4f5/ede2FFKZhywiO/'
    b'GGes2SUk5xS/GnSCXmiUA4jOWAAVcMlgK7tmr1mieS8uzqJnC6SQ88K3A3zpHIXUDoaO91A6'
    b'Cbwx7kuCqR0UJUNcIEPqzgfY4VVLX3QL7JslAaUFbjkMzTnbrYP6SSYHcWTfwWfhfXjiZHgy'
    b'7OmZWIclXVTuOQ4jpmvSOgTEqui6ljdilIdYYMLRBiPZbNSViWf3x3+RBRIG2fzOOFdosz7/'
    b'lCbiiqe0SMVxUECx6qOr+geI91rolxyCeAAAAABJRU5ErkJggg==')

#----------------------------------------------------------------------
Composition = PyEmbeddedImage(
    b'iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAQAAAC1+jfqAAAAOGVYSWZNTQAqAAAACAABh2kA'
    b'BAAAAAEAAAAaAAAAAAACoAIABAAAAAEAAAhWoAMABAAAAAEAAAhWAAAAAMFeALwAAAACYktH'
    b'RAD/h4/MvwAAAAd0SU1FB+oFEBQhNrv4wX0AAAAldEVYdGRhdGU6Y3JlYXRlADIwMjYtMDUt'
    b'MTZUMjA6MjY6MjArMDA6MDBi6Rk5AAAAJXRFWHRkYXRlOm1vZGlmeQAyMDI2LTA1LTE1VDE4'
    b'OjQ1OjI2KzAwOjAwfEynuwAAACh0RVh0ZGF0ZTp0aW1lc3RhbXAAMjAyNi0wNS0xNlQyMDoz'
    b'Mzo1NCswMDowMJ2MudQAAAASdEVYdGV4aWY6RXhpZk9mZnNldAAyNlMbomUAAAAZdEVYdGV4'
    b'aWY6UGl4ZWxYRGltZW5zaW9uADIxMzT4qaKHAAAAGXRFWHRleGlmOlBpeGVsWURpbWVuc2lv'
    b'bgAyMTM0QVJ5bwAAAD10RVh0aWNjOmNvcHlyaWdodABDb3B5cmlnaHQgMjAwNyBBcHBsZSBJ'
    b'bmMuLCBhbGwgcmlnaHRzIHJlc2VydmVkLp5m3CkAAAAjdEVYdGljYzpkZXNjcmlwdGlvbgBH'
    b'ZW5lcmljIFJHQiBQcm9maWxlGqc4jgAAAIVJREFUKM9jYKA5YGRgYGDYDud6YlOwHUUAXQkT'
    b'VDqaoYNBEGogCmBhYGBgZIhj6GcQZBBlLa77gE1BAMMEBgEGBsbEu+LnL6EYsorhPAsDA8N/'
    b'uIP+M/xjYEJS8B9iwgYGPoYJDIL/5ymV6H04ie4LuCN1GLoY3jMwdDGwkuZNggFFBwAAOi4a'
    b'3EkF/qYAAAAASUVORK5CYII=')

#----------------------------------------------------------------------
DefaultPreferences = PyEmbeddedImage(
    b'iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAAAAAA6mKC9AAAAIGNIUk0AAHomAACAhAAA+gAA'
    b'AIDoAAB1MAAA6mAAADqYAAAXcJy6UTwAAAACYktHRAD/h4/MvwAAAAd0SU1FB+oFEBQhNrv4'
    b'wX0AAAAldEVYdGRhdGU6Y3JlYXRlADIwMjYtMDUtMTZUMjA6MzA6NDErMDA6MDDOYbSNAAAA'
    b'JXRFWHRkYXRlOm1vZGlmeQAyMDI2LTA1LTE2VDIwOjI3OjQ4KzAwOjAwCfaNWwAAACh0RVh0'
    b'ZGF0ZTp0aW1lc3RhbXAAMjAyNi0wNS0xNlQyMDozMzo1NCswMDowMJ2MudQAAADRSURBVBjT'
    b'Zc8xSgNRFIXh/777kmIQkskwETMByyA24iKssgTB3k6QKdyCkB0kCxBSTxnsBKvswM5Gi8FR'
    b'ML6Za/ECFp7yaw6/8jcRBYF+ZoBp/QmIFzs8bxxYf/BwfLWoRayYfSh0SS+5PrvYekBVDf91'
    b'ejO53DoPGIY2xX1294S5eKDNdJXdbgbgAMw302VeVsN2D1oXy7ys0kAE932yystq1BJBzM3z'
    b'shoFADxYN14/PqdBkAjhKLy+JD/QthF6vOu4A7oDF+NSkX3u245/+wUqQD33FD+YGQAAAABJ'
    b'RU5ErkJggg==')

#----------------------------------------------------------------------
Inheritance = PyEmbeddedImage(
    b'iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAQAAAC1+jfqAAAAAmJLR0QA/4ePzL8AAAAJcEhZ'
    b'cwAALiMAAC4jAXilP3YAAAAHdElNRQfqBRAUITa7+MF9AAAAJXRFWHRkYXRlOmNyZWF0ZQAy'
    b'MDI2LTA1LTE1VDE4OjQ1OjI2KzAwOjAwDREfBwAAACV0RVh0ZGF0ZTptb2RpZnkAMjAyNi0w'
    b'NS0xNVQxODo0NToyNiswMDowMHxMp7sAAAAodEVYdGRhdGU6dGltZXN0YW1wADIwMjYtMDUt'
    b'MTZUMjA6MzM6NTQrMDA6MDCdjLnUAAAAr0lEQVQoz7WRPQrCcAzFfwnt4GLBvYcQ9AgOzi7i'
    b'6GI3DyOFOos38AbiEVw6dREXF3FRWv5x6AdaBSdfhiTw8vUCf4e8p0kTRZXXdoVhvgesK7Ik'
    b'bUYgczLb68WVHXJS7vqobAuBXPWkExvTFRSJ1ZtKSNFM6HF2sd9xQxvYjtQrx2IN4TUwkBUb'
    b'Zlofs3RJqCM5Wt8yO8hNfi/5oYOB7+cFghEB3hfl8gJY/P9JNZ4bKzz9TJuRHAAAAABJRU5E'
    b'rkJggg==')

#----------------------------------------------------------------------
NewClassDiagram = PyEmbeddedImage(
    b'iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAQAAAC1+jfqAAAAOGVYSWZNTQAqAAAACAABh2kA'
    b'BAAAAAEAAAAaAAAAAAACoAIABAAAAAEAAAhWoAMABAAAAAEAAAhWAAAAAMFeALwAAAACYktH'
    b'RAD/h4/MvwAAAAd0SU1FB+oFEBQhNrv4wX0AAAAldEVYdGRhdGU6Y3JlYXRlADIwMjYtMDUt'
    b'MTVUMTg6NDU6MjYrMDA6MDANER8HAAAAJXRFWHRkYXRlOm1vZGlmeQAyMDI2LTA1LTE1VDE4'
    b'OjQ1OjI2KzAwOjAwfEynuwAAACh0RVh0ZGF0ZTp0aW1lc3RhbXAAMjAyNi0wNS0xNlQyMDoz'
    b'Mzo1NCswMDowMJ2MudQAAAASdEVYdGV4aWY6RXhpZk9mZnNldAAyNlMbomUAAAAZdEVYdGV4'
    b'aWY6UGl4ZWxYRGltZW5zaW9uADIxMzT4qaKHAAAAGXRFWHRleGlmOlBpeGVsWURpbWVuc2lv'
    b'bgAyMTM0QVJ5bwAAAD10RVh0aWNjOmNvcHlyaWdodABDb3B5cmlnaHQgMjAwNyBBcHBsZSBJ'
    b'bmMuLCBhbGwgcmlnaHRzIHJlc2VydmVkLp5m3CkAAAAjdEVYdGljYzpkZXNjcmlwdGlvbgBH'
    b'ZW5lcmljIFJHQiBQcm9maWxlGqc4jgAAAQ9JREFUKM+F0btKA0EUxvH/zGwi67LGW6UBL3gh'
    b'AVE7bUUEC8HCN7Cz9EV8gwj2FmIRX0AIBIsVERsRFSxMpeIlrnvGYpPNRES/YobD/JjbgX+i'
    b'0qnaKpsccoDPRwY8AB+LLtoVjCI82z3PQUY8gHc+ya3qfYDo8nSbWpgRnQ6b/UdbFlC8lqno'
    b'pRfy9HaAwMDjAig8QihJheVR3jpHABaBmCumGSdf6tsrb8SNHQcAmjo3FCiySDIiAQ26ATww'
    b'zwzPxGC7ntnOJHUumGUQ4RcgzFHgizFn2QEKg2IKECzi/QRym9QwrWLobqJqn5xeGKRHr/nD'
    b'Or2aCqL76CQxrLd3sNDkWKe/BhiuCZyG/ZlvSIdJIlWbptoAAAAASUVORK5CYII=')

#----------------------------------------------------------------------
NewProject = PyEmbeddedImage(
    b'iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAQAAAC1+jfqAAAAOGVYSWZNTQAqAAAACAABh2kA'
    b'BAAAAAEAAAAaAAAAAAACoAIABAAAAAEAAAhWoAMABAAAAAEAAAhWAAAAAMFeALwAAAACYktH'
    b'RAD/h4/MvwAAAAd0SU1FB+oFEBQhNrv4wX0AAAAldEVYdGRhdGU6Y3JlYXRlADIwMjYtMDUt'
    b'MTVUMTg6NDU6MjYrMDA6MDANER8HAAAAJXRFWHRkYXRlOm1vZGlmeQAyMDI2LTA1LTE1VDE4'
    b'OjQ1OjI2KzAwOjAwfEynuwAAACh0RVh0ZGF0ZTp0aW1lc3RhbXAAMjAyNi0wNS0xNlQyMDoz'
    b'Mzo1NCswMDowMJ2MudQAAAASdEVYdGV4aWY6RXhpZk9mZnNldAAyNlMbomUAAAAZdEVYdGV4'
    b'aWY6UGl4ZWxYRGltZW5zaW9uADIxMzT4qaKHAAAAGXRFWHRleGlmOlBpeGVsWURpbWVuc2lv'
    b'bgAyMTM0QVJ5bwAAAD10RVh0aWNjOmNvcHlyaWdodABDb3B5cmlnaHQgMjAwNyBBcHBsZSBJ'
    b'bmMuLCBhbGwgcmlnaHRzIHJlc2VydmVkLp5m3CkAAAAjdEVYdGljYzpkZXNjcmlwdGlvbgBH'
    b'ZW5lcmljIFJHQiBQcm9maWxlGqc4jgAAAPlJREFUKM+FkT9KA1EQh795+95LBFmz3QoakPQe'
    b'IHWaNBZewTsIHiSt4BkUvIKkViwSEexMtRKEZHffjsWuYZWEzDQD881v/sEeE4B7FLc1PcaC'
    b'54lzH42i1KgAoAThmWmj4MnlYnh1ZwYZFQCWHuaBS4oxtpZadmeL4nTic0A55oako6aGEcBz'
    b'kszdJ0WjEBDVJgYgD/Nlv7x2AVAOiZtmYEFBvDs7Sly6mT5sIgMC1Xr9lhVF4NdpAwqmczDo'
    b'WbvtEgYErfLv96+y3AGARDbux/8UpAVoSD8WWQh/gFW9iECXW4ZuNipTtFX/wrT5xYqE14LH'
    b'fX/dYT8qGU9PV9n5+AAAAABJRU5ErkJggg==')

#----------------------------------------------------------------------
NewSequenceDiagram = PyEmbeddedImage(
    b'iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAQAAAC1+jfqAAAAOGVYSWZNTQAqAAAACAABh2kA'
    b'BAAAAAEAAAAaAAAAAAACoAIABAAAAAEAAAhWoAMABAAAAAEAAAhWAAAAAMFeALwAAAACYktH'
    b'RAD/h4/MvwAAAAd0SU1FB+oFEBQhNrv4wX0AAAAldEVYdGRhdGU6Y3JlYXRlADIwMjYtMDUt'
    b'MTVUMTg6NDU6MjYrMDA6MDANER8HAAAAJXRFWHRkYXRlOm1vZGlmeQAyMDI2LTA1LTE1VDE4'
    b'OjQ1OjI2KzAwOjAwfEynuwAAACh0RVh0ZGF0ZTp0aW1lc3RhbXAAMjAyNi0wNS0xNlQyMDoz'
    b'Mzo1NCswMDowMJ2MudQAAAASdEVYdGV4aWY6RXhpZk9mZnNldAAyNlMbomUAAAAZdEVYdGV4'
    b'aWY6UGl4ZWxYRGltZW5zaW9uADIxMzT4qaKHAAAAGXRFWHRleGlmOlBpeGVsWURpbWVuc2lv'
    b'bgAyMTM0QVJ5bwAAAD10RVh0aWNjOmNvcHlyaWdodABDb3B5cmlnaHQgMjAwNyBBcHBsZSBJ'
    b'bmMuLCBhbGwgcmlnaHRzIHJlc2VydmVkLp5m3CkAAAAjdEVYdGljYzpkZXNjcmlwdGlvbgBH'
    b'ZW5lcmljIFJHQiBQcm9maWxlGqc4jgAAAQ5JREFUKM+FkU8rRGEUxn/vn6HrzkyEDRIr3SnF'
    b'QrGdpCyUhW9gZ+mL+Aaj7C1kMb6AmpTFtZCNhN3MAmkwuO+xuHfee0k8i/d06nee5+0c+Ecq'
    b'Lc2s7XHIAQFvHrAAAYKekjpGUTnfvSiBRyzAK++UVvU+QHx5uk2r4hGdPpvDR1sCKLo1Gnr5'
    b'mQGGcsDBSHsBFJYyRK7ByiQveQQgOEWXKxaZg6i6V9v46OwUAEBzxg3T1CnjJlxIx0ekcsxQ'
    b'5ZFPEpzkY4WVPGBpZ9nf9tB3iAhYYhz5DVAYQuYRBMHZn4C7TVqYrBm9m23KU+EWBjeo14Ix'
    b'nXqrML6PTxLDet9BoMex9j82XBMWDvanvgAiaks1ALGwkAAAAABJRU5ErkJggg==')

#----------------------------------------------------------------------
NewUseCaseDiagram = PyEmbeddedImage(
    b'iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAQAAAC1+jfqAAAAOGVYSWZNTQAqAAAACAABh2kA'
    b'BAAAAAEAAAAaAAAAAAACoAIABAAAAAEAAAhWoAMABAAAAAEAAAhWAAAAAMFeALwAAAACYktH'
    b'RAD/h4/MvwAAAAd0SU1FB+oFEBQhNrv4wX0AAAAldEVYdGRhdGU6Y3JlYXRlADIwMjYtMDUt'
    b'MTVUMTg6NDU6MjYrMDA6MDANER8HAAAAJXRFWHRkYXRlOm1vZGlmeQAyMDI2LTA1LTE1VDE4'
    b'OjQ1OjI2KzAwOjAwfEynuwAAACh0RVh0ZGF0ZTp0aW1lc3RhbXAAMjAyNi0wNS0xNlQyMDoz'
    b'Mzo1NCswMDowMJ2MudQAAAASdEVYdGV4aWY6RXhpZk9mZnNldAAyNlMbomUAAAAZdEVYdGV4'
    b'aWY6UGl4ZWxYRGltZW5zaW9uADIxMzT4qaKHAAAAGXRFWHRleGlmOlBpeGVsWURpbWVuc2lv'
    b'bgAyMTM0QVJ5bwAAAD10RVh0aWNjOmNvcHlyaWdodABDb3B5cmlnaHQgMjAwNyBBcHBsZSBJ'
    b'bmMuLCBhbGwgcmlnaHRzIHJlc2VydmVkLp5m3CkAAAAjdEVYdGljYzpkZXNjcmlwdGlvbgBH'
    b'ZW5lcmljIFJHQiBQcm9maWxlGqc4jgAAAQpJREFUKM+FkbtKA1EQhr9zibJZFiJGCw2IlWwa'
    b'xUpbCaKFYOEb2Fn6Ir5BBHsLsYgvIKQRXQs7C7UJphLxEuPOsdjk5CiiU8wwzDf/zzDwT6ii'
    b'tAZtj2OOiHj3gAWIcOiaW8Mokov96xJ4xAK88UGpoQ8BspvzXdqJR3SRtisnOw5QvNRp6pVn'
    b'xiiPAIGJxyVQaGJIpcnqLK8jC8Ahig5lNpiimiYH9a1+dy8AAM0VNSwpDT5nJKbrLfAyDqFP'
    b'jrhvZw7H01wiLOOCpQAQFqmgmEN+AxQGywIgOMT+BOQub2MGzeT9fMs9Bb8wyLhej6q6MFdx'
    b'9pCd5YbNoYKDHqfan2S4JQ4e9md8AZRdSqqPgqr4AAAAAElFTkSuQmCC')

#----------------------------------------------------------------------
Note = PyEmbeddedImage(
    b'iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAQAAAC1+jfqAAAAOGVYSWZNTQAqAAAACAABh2kA'
    b'BAAAAAEAAAAaAAAAAAACoAIABAAAAAEAAAhWoAMABAAAAAEAAAhWAAAAAMFeALwAAAACYktH'
    b'RAD/h4/MvwAAAAd0SU1FB+oFEBQhNrv4wX0AAAAldEVYdGRhdGU6Y3JlYXRlADIwMjYtMDUt'
    b'MTVUMTg6NDU6MjYrMDA6MDANER8HAAAAJXRFWHRkYXRlOm1vZGlmeQAyMDI2LTA1LTE1VDE4'
    b'OjQ1OjI2KzAwOjAwfEynuwAAACh0RVh0ZGF0ZTp0aW1lc3RhbXAAMjAyNi0wNS0xNlQyMDoz'
    b'Mzo1NCswMDowMJ2MudQAAAASdEVYdGV4aWY6RXhpZk9mZnNldAAyNlMbomUAAAAZdEVYdGV4'
    b'aWY6UGl4ZWxYRGltZW5zaW9uADIxMzT4qaKHAAAAGXRFWHRleGlmOlBpeGVsWURpbWVuc2lv'
    b'bgAyMTM0QVJ5bwAAAD10RVh0aWNjOmNvcHlyaWdodABDb3B5cmlnaHQgMjAwNyBBcHBsZSBJ'
    b'bmMuLCBhbGwgcmlnaHRzIHJlc2VydmVkLp5m3CkAAAAjdEVYdGljYzpkZXNjcmlwdGlvbgBH'
    b'ZW5lcmljIFJHQiBQcm9maWxlGqc4jgAAALxJREFUKM+Fkb0OgkAQhL9dDEYan0FfwcpSO3lf'
    b'pfU1bCi1MTE2EAVuLYA7/AvT3ORmbnZyCyMQyP5IOwAmAChbXai1gtE8yLgOE2ayLzb3Tk6Y'
    b'l6QcGSSA1hQdjUAQlIgqGHBUHWvAiEmJOFBpaKsoiiAACQUlySBBPY180LADhr2dPb46WP/0'
    b'0yCoH0aI9QbpO1hrMOr2orXXXAxz5szhzBGzBqaUYRdLXan6rxaenDlxCyNyl7uxxf7GC6v6'
    b'PWF12jrXAAAAAElFTkSuQmCC')

#----------------------------------------------------------------------
NoteAssociation = PyEmbeddedImage(
    b'iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAQAAAC1+jfqAAAAOGVYSWZNTQAqAAAACAABh2kA'
    b'BAAAAAEAAAAaAAAAAAACoAIABAAAAAEAAAhWoAMABAAAAAEAAAhWAAAAAMFeALwAAAACYktH'
    b'RAD/h4/MvwAAAAd0SU1FB+oFEBQhNrv4wX0AAAAldEVYdGRhdGU6Y3JlYXRlADIwMjYtMDUt'
    b'MTVUMTg6NDU6MjYrMDA6MDANER8HAAAAJXRFWHRkYXRlOm1vZGlmeQAyMDI2LTA1LTE1VDE4'
    b'OjQ1OjI2KzAwOjAwfEynuwAAACh0RVh0ZGF0ZTp0aW1lc3RhbXAAMjAyNi0wNS0xNlQyMDoz'
    b'Mzo1NCswMDowMJ2MudQAAAASdEVYdGV4aWY6RXhpZk9mZnNldAAyNlMbomUAAAAZdEVYdGV4'
    b'aWY6UGl4ZWxYRGltZW5zaW9uADIxMzT4qaKHAAAAGXRFWHRleGlmOlBpeGVsWURpbWVuc2lv'
    b'bgAyMTM0QVJ5bwAAAD10RVh0aWNjOmNvcHlyaWdodABDb3B5cmlnaHQgMjAwNyBBcHBsZSBJ'
    b'bmMuLCBhbGwgcmlnaHRzIHJlc2VydmVkLp5m3CkAAAAjdEVYdGljYzpkZXNjcmlwdGlvbgBH'
    b'ZW5lcmljIFJHQiBQcm9maWxlGqc4jgAAAFNJREFUKM/dzysKgFAARNHDw2DRpvtfg8HgZzsi'
    b'BrFo0PAMGtyACF4YGLhThh9R6UGjBZ36NglKhUVmk9oFwSG1ys3GcA8jovjoVySYTBi+vvkm'
    b'JxONFBVQyLTGAAAAAElFTkSuQmCC')

#----------------------------------------------------------------------
OpenProject = PyEmbeddedImage(
    b'iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAQAAAC1+jfqAAAAOGVYSWZNTQAqAAAACAABh2kA'
    b'BAAAAAEAAAAaAAAAAAACoAIABAAAAAEAAAhWoAMABAAAAAEAAAhWAAAAAMFeALwAAAACYktH'
    b'RAD/h4/MvwAAAAd0SU1FB+oFEBQhNrv4wX0AAAAldEVYdGRhdGU6Y3JlYXRlADIwMjYtMDUt'
    b'MTVUMTg6NDU6MjYrMDA6MDANER8HAAAAJXRFWHRkYXRlOm1vZGlmeQAyMDI2LTA1LTE1VDE4'
    b'OjQ1OjI2KzAwOjAwfEynuwAAACh0RVh0ZGF0ZTp0aW1lc3RhbXAAMjAyNi0wNS0xNlQyMDoz'
    b'Mzo1NCswMDowMJ2MudQAAAASdEVYdGV4aWY6RXhpZk9mZnNldAAyNlMbomUAAAAZdEVYdGV4'
    b'aWY6UGl4ZWxYRGltZW5zaW9uADIxMzT4qaKHAAAAGXRFWHRleGlmOlBpeGVsWURpbWVuc2lv'
    b'bgAyMTM0QVJ5bwAAAD10RVh0aWNjOmNvcHlyaWdodABDb3B5cmlnaHQgMjAwNyBBcHBsZSBJ'
    b'bmMuLCBhbGwgcmlnaHRzIHJlc2VydmVkLp5m3CkAAAAjdEVYdGljYzpkZXNjcmlwdGlvbgBH'
    b'ZW5lcmljIFJHQiBQcm9maWxlGqc4jgAAAQZJREFUKM+F0b9Kw1AUx/HvuWkkpYklHRwkVCc3'
    b'QfzzAI6+Q8HRF9DJh/AJXF0FF1/AUcFNEMFB3NSA0cakN/c4JEYslf7Gw4ff5ZwLcyJwOTXa'
    b'mwEidolwXPE0jTsAbHMmPeB84cjkACplYV+NUgMJbP7xoqIb7lRLFYcwEP9Qbxvgy8PjsedC'
    b'MMsq0dvqu1/sS9K3NIBK07F1IYr4nwfB5paKl9kJP8CmSXjSdwYgWEpWpAv0WGyBi7s7az6A'
    b'Aq5eQNEWiJSaohji5s3fdAAMmd6pU491GYj+Aaa+1rOO1ZJzr25Wg37Fk8o3OCLagpKiBdXN'
    b'cDQM63nbkHHdAjJ3Me9X/803VKpeyt97MQQAAAAASUVORK5CYII=')

#----------------------------------------------------------------------
Pointer = PyEmbeddedImage(
    b'iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAQAAAC1+jfqAAAAOGVYSWZNTQAqAAAACAABh2kA'
    b'BAAAAAEAAAAaAAAAAAACoAIABAAAAAEAAAhWoAMABAAAAAEAAAhWAAAAAMFeALwAAAACYktH'
    b'RAD/h4/MvwAAAAd0SU1FB+oFEBQhNrv4wX0AAAAldEVYdGRhdGU6Y3JlYXRlADIwMjYtMDUt'
    b'MTVUMTg6NDU6MjYrMDA6MDANER8HAAAAJXRFWHRkYXRlOm1vZGlmeQAyMDI2LTA1LTE1VDE4'
    b'OjQ1OjI2KzAwOjAwfEynuwAAACh0RVh0ZGF0ZTp0aW1lc3RhbXAAMjAyNi0wNS0xNlQyMDoz'
    b'Mzo1NCswMDowMJ2MudQAAAASdEVYdGV4aWY6RXhpZk9mZnNldAAyNlMbomUAAAAZdEVYdGV4'
    b'aWY6UGl4ZWxYRGltZW5zaW9uADIxMzT4qaKHAAAAGXRFWHRleGlmOlBpeGVsWURpbWVuc2lv'
    b'bgAyMTM0QVJ5bwAAAD10RVh0aWNjOmNvcHlyaWdodABDb3B5cmlnaHQgMjAwNyBBcHBsZSBJ'
    b'bmMuLCBhbGwgcmlnaHRzIHJlc2VydmVkLp5m3CkAAAAjdEVYdGljYzpkZXNjcmlwdGlvbgBH'
    b'ZW5lcmljIFJHQiBQcm9maWxlGqc4jgAAAXlJREFUKM+FkT1PU2EAhZ/7vre3QHPbq0WoRSwW'
    b'4RLQkgCDdmkiCTEYXKoObG4d/ANuwixxYCFhYCAkTIQQMTGBHwAlaQiDTWwHUw1EKNKkH/bz'
    b'ZbhxUIee7SRPznAeaBPNR4FV7qCAJoIEub8AXQGuh5rlzUbPtfpblvDRBMq8cBYMap7XO8+i'
    b'27lCuifVlxr50v1jpjhNhm8ASEmzUX08/sjyV+2z2Nd476vbc0/MD0f3W6cOIDD4WQnHY8YY'
    b'k0RkwLzo36xltsqNKgBigDqtw1TyihYCi05O89n3id+77DoLlyiGaznTnu1DoaEIuGaxD2ol'
    b'yTwbSPByRinvfx6xFL/oBMkED0iqfJE4Eqp00Liq26GpdH2l5HGH0GCIqOuk8t3vnOFGIGK3'
    b'ct3LPLWOE+qj+qw+qYV92WU7wCA6Lp0RTGC0Y++l2lTvWoOLCOPPoQYGEt0pQX09XAmuYYLx'
    b'r5obgIbmJcZNkLz5395dBDoCieBeO9UA12h9cZnINBZEAAAAAElFTkSuQmCC')

#----------------------------------------------------------------------
Realization = PyEmbeddedImage(
    b'iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAQAAAC1+jfqAAAAOGVYSWZNTQAqAAAACAABh2kA'
    b'BAAAAAEAAAAaAAAAAAACoAIABAAAAAEAAAhWoAMABAAAAAEAAAhWAAAAAMFeALwAAAACYktH'
    b'RAD/h4/MvwAAAAd0SU1FB+oFEBQhNrv4wX0AAAAldEVYdGRhdGU6Y3JlYXRlADIwMjYtMDUt'
    b'MTVUMTg6NDU6MjYrMDA6MDANER8HAAAAJXRFWHRkYXRlOm1vZGlmeQAyMDI2LTA1LTE1VDE4'
    b'OjQ1OjI2KzAwOjAwfEynuwAAACh0RVh0ZGF0ZTp0aW1lc3RhbXAAMjAyNi0wNS0xNlQyMDoz'
    b'Mzo1NCswMDowMJ2MudQAAAASdEVYdGV4aWY6RXhpZk9mZnNldAAyNlMbomUAAAAZdEVYdGV4'
    b'aWY6UGl4ZWxYRGltZW5zaW9uADIxMzT4qaKHAAAAGXRFWHRleGlmOlBpeGVsWURpbWVuc2lv'
    b'bgAyMTM0QVJ5bwAAAD10RVh0aWNjOmNvcHlyaWdodABDb3B5cmlnaHQgMjAwNyBBcHBsZSBJ'
    b'bmMuLCBhbGwgcmlnaHRzIHJlc2VydmVkLp5m3CkAAAAjdEVYdGljYzpkZXNjcmlwdGlvbgBH'
    b'ZW5lcmljIFJHQiBQcm9maWxlGqc4jgAAAK1JREFUKM9jYKA/YGNgY2BjYGDgx6OGkYFJhYGB'
    b'gZlBHJusGIOYuelccUcGFhEGBgYWBmZ2BiaGf0gK+Bi4LWPbjf1ZVO4//f3iHwMzK/N/0X/8'
    b'DEIMAgxcDBIMzF+keJSdfA24NAzlAz/zvzzBxMjAiNs1/xkYWP7//f8KWUzyNavBZ+ZjH46s'
    b'PTr92zmG/1gdaTJH3IGBGeJIHN5UZmBgYGaQwBVQrAQCisoAAMxSIffVP1fFAAAAAElFTkSu'
    b'QmCC')

#----------------------------------------------------------------------
Redo = PyEmbeddedImage(
    b'iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAQAAAC1+jfqAAAAAmJLR0QA/4ePzL8AAAAJcEhZ'
    b'cwAALiMAAC4jAXilP3YAAAAHdElNRQfqBRAUITa7+MF9AAAAJXRFWHRkYXRlOmNyZWF0ZQAy'
    b'MDI2LTA1LTE1VDE4OjQ1OjI2KzAwOjAwDREfBwAAACV0RVh0ZGF0ZTptb2RpZnkAMjAyNi0w'
    b'NS0xNVQxODo0NToyNiswMDowMHxMp7sAAAAodEVYdGRhdGU6dGltZXN0YW1wADIwMjYtMDUt'
    b'MTZUMjA6MzM6NTQrMDA6MDCdjLnUAAABDklEQVQoz4WRPUsDURBFz+x7u3GNRiWIgmIrdjYR'
    b'hfwCCxuxsLbQytbKv2AdLCxsNRZiZaWQwt5UQgohGMQPUqnZXd9YbIhRsmSqGc7lznAHhpT0'
    b'D7W+vvxf0IMhCfGvzP6Bgk/OiOePxofxJlXOkR42QVBQ1UdpWpu3EzLmtdqt6dTB4oK8uZ/8'
    b'WNFVFpn5Ln5FcuUfJzhsDVDbydXXdV9HeKDAGrccuWs6L8xiQQj9+oY7oELVPXslljmjLUTM'
    b's4XUWJKbudeKnnABgojT9N5d0vUU9XSBhl56AKgKdGFXsIPkuDOJY29AkhZKmDfzmRW1hSLy'
    b'pAWP7YECr8w44Xu+OZXtkKBOo2TYW7PqBxRMUZI5Q6XbAAAAAElFTkSuQmCC')

#----------------------------------------------------------------------
SaveProject = PyEmbeddedImage(
    b'iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAQAAAC1+jfqAAAAOGVYSWZNTQAqAAAACAABh2kA'
    b'BAAAAAEAAAAaAAAAAAACoAIABAAAAAEAAAhWoAMABAAAAAEAAAhWAAAAAMFeALwAAAACYktH'
    b'RAD/h4/MvwAAAAd0SU1FB+oFEBQhNrv4wX0AAAAldEVYdGRhdGU6Y3JlYXRlADIwMjYtMDUt'
    b'MTVUMTg6NDU6MjYrMDA6MDANER8HAAAAJXRFWHRkYXRlOm1vZGlmeQAyMDI2LTA1LTE1VDE4'
    b'OjQ1OjI2KzAwOjAwfEynuwAAACh0RVh0ZGF0ZTp0aW1lc3RhbXAAMjAyNi0wNS0xNlQyMDoz'
    b'Mzo1NCswMDowMJ2MudQAAAASdEVYdGV4aWY6RXhpZk9mZnNldAAyNlMbomUAAAAZdEVYdGV4'
    b'aWY6UGl4ZWxYRGltZW5zaW9uADIxMzT4qaKHAAAAGXRFWHRleGlmOlBpeGVsWURpbWVuc2lv'
    b'bgAyMTM0QVJ5bwAAAD10RVh0aWNjOmNvcHlyaWdodABDb3B5cmlnaHQgMjAwNyBBcHBsZSBJ'
    b'bmMuLCBhbGwgcmlnaHRzIHJlc2VydmVkLp5m3CkAAAAjdEVYdGljYzpkZXNjcmlwdGlvbgBH'
    b'ZW5lcmljIFJHQiBQcm9maWxlGqc4jgAAAPJJREFUKM+F0b0uREEYgOFn9uyPaLZwEn9BdBJR'
    b'cBOidBk6V6PTugRuBBEJirUSgvgpdp09Z0dh1qHar5x55503+ZgygTMQ5ba0fTi1rWcM9jRB'
    b'btd1GAx2yqzQDZ5joecCCVh3pBiOZhc64d2xw2EjVuf29ScA5FFA9KaawYalf0BQuJH5cqCl'
    b'YCzWX6AhugdzhsLPbQ1EK+ZV6TDzoCf4Z5jx6ClVLOr8pv0C0chXAkbaf4GAkIR1cgPxB3gX'
    b'9S3LNJMh8+nSmlAbMgOruul9y6ssWZt0uc0PPtpX6p7KZlHepYYxL8VJ609FUCqnrXky3yOk'
    b'TQqc7MiAAAAAAElFTkSuQmCC')

#----------------------------------------------------------------------
SequenceDiagramInstance = PyEmbeddedImage(
    b'iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAQAAAC1+jfqAAAAOGVYSWZNTQAqAAAACAABh2kA'
    b'BAAAAAEAAAAaAAAAAAACoAIABAAAAAEAAAhWoAMABAAAAAEAAAhWAAAAAMFeALwAAAACYktH'
    b'RAD/h4/MvwAAAAd0SU1FB+oFEBQhNrv4wX0AAAAldEVYdGRhdGU6Y3JlYXRlADIwMjYtMDUt'
    b'MTVUMTg6NDU6MjYrMDA6MDANER8HAAAAJXRFWHRkYXRlOm1vZGlmeQAyMDI2LTA1LTE1VDE4'
    b'OjQ1OjI2KzAwOjAwfEynuwAAACh0RVh0ZGF0ZTp0aW1lc3RhbXAAMjAyNi0wNS0xNlQyMDoz'
    b'Mzo1NCswMDowMJ2MudQAAAASdEVYdGV4aWY6RXhpZk9mZnNldAAyNlMbomUAAAAZdEVYdGV4'
    b'aWY6UGl4ZWxYRGltZW5zaW9uADIxMzT4qaKHAAAAGXRFWHRleGlmOlBpeGVsWURpbWVuc2lv'
    b'bgAyMTM0QVJ5bwAAAD10RVh0aWNjOmNvcHlyaWdodABDb3B5cmlnaHQgMjAwNyBBcHBsZSBJ'
    b'bmMuLCBhbGwgcmlnaHRzIHJlc2VydmVkLp5m3CkAAAAjdEVYdGljYzpkZXNjcmlwdGlvbgBH'
    b'ZW5lcmljIFJHQiBQcm9maWxlGqc4jgAAANNJREFUKM+t0D1OAlEUxfHfG4aBBE0gfrR2hLAE'
    b'd+BO3IK9iYtxAW7ASGJnoY3UNhaKEhiG8J6FRmBMtPF095z/PTe5/KHAhailqAWVhcyZHLTT'
    b'yaonbS6mF1dKn0C1u39+MAySgCRInu+frtslGUSFuZGWR2MtI3OFiK8GhFxXsIOgq2kR0hpo'
    b'KMtO1V9N7WVMY19sLMo8fQPF6+T0vSM1482Q44dlJsRpMVmfWLqFscs7DidHv/xlYLBtNH4g'
    b'M7PNMavFPb1tI68Bb/XCOpD8uz4A0ys930AoD4EAAAAASUVORK5CYII=')

#----------------------------------------------------------------------
SequenceDiagramMessage = PyEmbeddedImage(
    b'iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAQAAAC1+jfqAAAAOGVYSWZNTQAqAAAACAABh2kA'
    b'BAAAAAEAAAAaAAAAAAACoAIABAAAAAEAAAhWoAMABAAAAAEAAAhWAAAAAMFeALwAAAACYktH'
    b'RAD/h4/MvwAAAAd0SU1FB+oFEBQhNrv4wX0AAAAldEVYdGRhdGU6Y3JlYXRlADIwMjYtMDUt'
    b'MTVUMTg6NDU6MjYrMDA6MDANER8HAAAAJXRFWHRkYXRlOm1vZGlmeQAyMDI2LTA1LTE1VDE4'
    b'OjQ1OjI2KzAwOjAwfEynuwAAACh0RVh0ZGF0ZTp0aW1lc3RhbXAAMjAyNi0wNS0xNlQyMDoz'
    b'Mzo1NCswMDowMJ2MudQAAAASdEVYdGV4aWY6RXhpZk9mZnNldAAyNlMbomUAAAAZdEVYdGV4'
    b'aWY6UGl4ZWxYRGltZW5zaW9uADIxMzT4qaKHAAAAGXRFWHRleGlmOlBpeGVsWURpbWVuc2lv'
    b'bgAyMTM0QVJ5bwAAAD10RVh0aWNjOmNvcHlyaWdodABDb3B5cmlnaHQgMjAwNyBBcHBsZSBJ'
    b'bmMuLCBhbGwgcmlnaHRzIHJlc2VydmVkLp5m3CkAAAAjdEVYdGljYzpkZXNjcmlwdGlvbgBH'
    b'ZW5lcmljIFJHQiBQcm9maWxlGqc4jgAAAQFJREFUKM+1kU0rRHEchZ//y9y5V15mLpky0x1q'
    b'Il2NLbFQmlKIbKx9Br6Bhb2V8hF8C2Us7EhZKeSl1MWMXFPu/dnMKKzn7M7pbM5zoOtSv60l'
    b'hwEUT+3EgEW3m5qUD6ZJuMXgEwPGQcCXeRQLqqQqomXps/h+U0ifMQQYS0Z/rcqWKrOuZjFy'
    b'XNtb3vYmrh9bD/2SxSiSMlPEDKs37rGiqrWVYLI6tpYZvbsyLzpF+mScXpo0EAyLcUHIEQ4F'
    b'G07oYiuoC9nprNiVTW8gbJQuo5Ojs4PmeYTKA/IzM6blzBz6Xn3/9dRPIuxfLC5zMEi2CBhG'
    b'/nNz6cFg0eS7f1JH39/aRZq5wco/AAAAAElFTkSuQmCC')

#----------------------------------------------------------------------
Text = PyEmbeddedImage(
    b'iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAQAAAC1+jfqAAAAOGVYSWZNTQAqAAAACAABh2kA'
    b'BAAAAAEAAAAaAAAAAAACoAIABAAAAAEAAAhWoAMABAAAAAEAAAhWAAAAAMFeALwAAAACYktH'
    b'RAD/h4/MvwAAAAd0SU1FB+oFEBQhNrv4wX0AAAAldEVYdGRhdGU6Y3JlYXRlADIwMjYtMDUt'
    b'MTVUMTg6NDU6MjYrMDA6MDANER8HAAAAJXRFWHRkYXRlOm1vZGlmeQAyMDI2LTA1LTE1VDE4'
    b'OjQ1OjI2KzAwOjAwfEynuwAAACh0RVh0ZGF0ZTp0aW1lc3RhbXAAMjAyNi0wNS0xNlQyMDoz'
    b'Mzo1NCswMDowMJ2MudQAAAASdEVYdGV4aWY6RXhpZk9mZnNldAAyNlMbomUAAAAZdEVYdGV4'
    b'aWY6UGl4ZWxYRGltZW5zaW9uADIxMzT4qaKHAAAAGXRFWHRleGlmOlBpeGVsWURpbWVuc2lv'
    b'bgAyMTM0QVJ5bwAAAD10RVh0aWNjOmNvcHlyaWdodABDb3B5cmlnaHQgMjAwNyBBcHBsZSBJ'
    b'bmMuLCBhbGwgcmlnaHRzIHJlc2VydmVkLp5m3CkAAAAjdEVYdGljYzpkZXNjcmlwdGlvbgBH'
    b'ZW5lcmljIFJHQiBQcm9maWxlGqc4jgAAAOBJREFUKM+FkTFKQ2EQhL/d/JIELRIUFUTRQtKk'
    b'sLARbATxOF7BgLcKKVJ7gJTamOKhkFSx+bNjkWd4zyhZ2J1lGYZhB7bVDU4D27gbjnGNtfmC'
    b'Dvd0fjHmjJgnknHC5+Pd07kLEGCA8RbjwcHzB8mY+n7/1vdYIloc805ml0t/6U/dIhlgEpkl'
    b'q5nJZIQJhNeN1RGoE7RGrW/pZwkClR0VglflrTI3FP6jJAGyJkcEYoc2hwRNCmRgJHEWxWSs'
    b'C1NpcKXxqsXkNIry1V0e6FacgTFjyKwBvTKWv8O62ho23y0DR+jUlEXnAAAAAElFTkSuQmCC')

#----------------------------------------------------------------------
Undo = PyEmbeddedImage(
    b'iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAQAAAC1+jfqAAAAAmJLR0QA/4ePzL8AAAAJcEhZ'
    b'cwAALiMAAC4jAXilP3YAAAAHdElNRQfqBRAUITa7+MF9AAAAJXRFWHRkYXRlOmNyZWF0ZQAy'
    b'MDI2LTA1LTE1VDE4OjQ1OjI2KzAwOjAwDREfBwAAACV0RVh0ZGF0ZTptb2RpZnkAMjAyNi0w'
    b'NS0xNVQxODo0NToyNiswMDowMHxMp7sAAAAodEVYdGRhdGU6dGltZXN0YW1wADIwMjYtMDUt'
    b'MTZUMjA6MzM6NTQrMDA6MDCdjLnUAAABF0lEQVQoz4WQvUoDURBGz+zuJWhADCgmhaSwFQQL'
    b'q2hvJxjUUgSNb+Ab2NupL2CjoO8QUEQEyzQxEJUIiiYmRPbnjsXGJAtKvmaGmTMfMwMjJL9J'
    b'eahYSAJDLYNHNwk55xzwyBETxqRdQwoTu5Z7g3LBK5mszdIOW0E7b2cVaYnvE8U+XkREdyzY'
    b'0lUxvFcb1YrcpO/mm51I/AhwN3hg5jMsyxMLLNNgXNeDteePyZpn1e4gcIqN98mwyX1wa3IU'
    b'2XMPly6/uv0zT9B4Z1FVgKJsT5VWXirqxECJfQRBlTheUe3kpxW8wRNK/ewYN9BrUrskgIEc'
    b'HKh5ncXhVyd1hp1LNfUt97cDZPium9Cl8B8Qor7tXTZCP8oVYUOIAXxmAAAAAElFTkSuQmCC')

#----------------------------------------------------------------------
UseCase = PyEmbeddedImage(
    b'iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAQAAAC1+jfqAAAAAmJLR0QA/4ePzL8AAAAJcEhZ'
    b'cwAALiMAAC4jAXilP3YAAAAHdElNRQfqBRAUITa7+MF9AAAAJXRFWHRkYXRlOmNyZWF0ZQAy'
    b'MDI2LTA1LTE1VDE4OjQ1OjI2KzAwOjAwDREfBwAAACV0RVh0ZGF0ZTptb2RpZnkAMjAyNi0w'
    b'NS0xNVQxODo0NToyNiswMDowMHxMp7sAAAAodEVYdGRhdGU6dGltZXN0YW1wADIwMjYtMDUt'
    b'MTZUMjA6MzM6NTQrMDA6MDCdjLnUAAABI0lEQVQoz4WRMUtCURiGn++ce8MLUkEF1RQNjTVe'
    b'IpF+QFs0COEYRottIU1BOdZ4oamGDML/IGWEY0RDQkVTgQUWwpW8x9OQigThu37PO7zPBwMi'
    b'AME/x8wvEHRIO80ck8AbD7x2Eem0Z9lkSUI+gDHrUSbgCcABIMGhPMqOvo01oBk3C3bLnrPN'
    b'NUgAMxSlNLTbCjUu0MLget/7NskqLwpIidX5KBRGSZNmGCEKdV4gBQ4OPjeN9wIeJQDWSHLJ'
    b'Uc2r4KNVd1KDdm/eXt9URUSFxfh4lnWKAFxQ5Zj4BD4VjALOLCanPUudU074wqI9k7NQAL0C'
    b'n9yz0V6Wmqq7kVJmxPrmwM6T5Y4+URkS0uyIinFFwDN/VE/1VFf7VA961sD8AF22YI75uMd1'
    b'AAAAAElFTkSuQmCC')

