from wx.lib.embeddedimage import PyEmbeddedImage
#----------------------------------------------------------------------
Actor = PyEmbeddedImage(
    b'iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAQAAADZc7J/AAAAOGVYSWZNTQAqAAAACAABh2kA'
    b'BAAAAAEAAAAaAAAAAAACoAIABAAAAAEAAAhWoAMABAAAAAEAAAhWAAAAAMFeALwAAAACYktH'
    b'RAD/h4/MvwAAAAd0SU1FB+oFDhcEAVk2KmAAAAAldEVYdGRhdGU6Y3JlYXRlADIwMjYtMDUt'
    b'MTRUMjI6NTc6MzIrMDA6MDAY2eYbAAAAJXRFWHRkYXRlOm1vZGlmeQAyMDI2LTA1LTE0VDIy'
    b'OjM5OjAzKzAwOjAwtwCoAAAAACh0RVh0ZGF0ZTp0aW1lc3RhbXAAMjAyNi0wNS0xNFQyMzow'
    b'NDowMSswMDowMMYArMIAAAASdEVYdGV4aWY6RXhpZk9mZnNldAAyNlMbomUAAAAZdEVYdGV4'
    b'aWY6UGl4ZWxYRGltZW5zaW9uADIxMzT4qaKHAAAAGXRFWHRleGlmOlBpeGVsWURpbWVuc2lv'
    b'bgAyMTM0QVJ5bwAAAD10RVh0aWNjOmNvcHlyaWdodABDb3B5cmlnaHQgMjAwNyBBcHBsZSBJ'
    b'bmMuLCBhbGwgcmlnaHRzIHJlc2VydmVkLp5m3CkAAAAjdEVYdGljYzpkZXNjcmlwdGlvbgBH'
    b'ZW5lcmljIFJHQiBQcm9maWxlGqc4jgAAAXlJREFUSMfdlDEvQ1EYhp97b4deYhBlUIztQMQg'
    b'Bv+ggw1JLZLqYmgkukhEMEl1Jw2DoWksWET5A020NfUHkLA0jVQ6uJW4PQbtxe1xkRrKO5yc'
    b'75zvffKd8+Uc+PNS3gdpaxYAxrnGBZj4yDTtNqQ2IbVXlIc8ZYoUKZOht2HX7Ol2gIddlnHD'
    b'OqD61W01pvhgDcBNlB16PhpcNoDOJGGG2DAf3B1PcTEFwq8HVYNuNolQQHeu4JYQVyyRGPNW'
    b'dXwA+Ax9eIAEEbIscOcMgCxBzpg1ksdekaJCRaROBqtJZjhljpxjF6yb7mOLkFKoHOVGEROF'
    b'rmkxwh6rlOw9aAJYiE5WiKJrNTBVDOLEeGy2SwAWwsU+8/WlA8KYMrvsDhpJz9xbSyVMWJTY'
    b'pQAL8VadAnAjS5UDfqL2B9SotQZIsNcaIEe+NYD2VUb7d+EXAArSJ/cdgAAEtfrsE7kcAOf0'
    b'c4nCIRfOBUpkfeKmNUofs8Pp0rY4wL/VC4+SXlJGIChLAAAAAElFTkSuQmCC')

#----------------------------------------------------------------------
Aggregation = PyEmbeddedImage(
    b'iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAQAAADZc7J/AAAAAmJLR0QA/4ePzL8AAAAJcEhZ'
    b'cwAALiMAAC4jAXilP3YAAAAHdElNRQfqBQ4XBAFZNipgAAAAJXRFWHRkYXRlOmNyZWF0ZQAy'
    b'MDI2LTA1LTE0VDIyOjU3OjMyKzAwOjAwGNnmGwAAACV0RVh0ZGF0ZTptb2RpZnkAMjAyNi0w'
    b'NS0xNFQyMjoxNTozOSswMDowMN+vqeIAAAAodEVYdGRhdGU6dGltZXN0YW1wADIwMjYtMDUt'
    b'MTRUMjM6MDQ6MDErMDA6MDDGAKzCAAAA6UlEQVRIx+2TSw6CMBRFz2v8xWhUcCWO3YWbMG7G'
    b'bThyFWxERxoVouJnYuvAQkD8NMYhdwRpz3mP8gplyoBkX4L0afiLIMgtuCokhwtdGhw4uStU'
    b'rrqPsKFJq9jRxw7s1j6aEFD4XIjdupACTqJYxMev+JgKT/iQADQ78ZRH7QMbswKsoI0k+ENh'
    b'9Gw7GDGlinmJV5gzQZN2UNhWxxgM+k19kxDJGXgYovQTQEl32dzX39QHIWadPYMQnx6R1Sl6'
    b'5noLcUj2N/poogfO1XWY7CRmFEc67vjzKGNH+eyK//My5RXu17lMGYA7vLNKY/FSJywAAAAA'
    b'SUVORK5CYII=')

#----------------------------------------------------------------------
Association = PyEmbeddedImage(
    b'iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAQAAADZc7J/AAAAAmJLR0QA/4ePzL8AAAAJcEhZ'
    b'cwAALiMAAC4jAXilP3YAAAAHdElNRQfqBQ4XBAFZNipgAAAAJXRFWHRkYXRlOmNyZWF0ZQAy'
    b'MDI2LTA1LTE0VDIyOjU3OjMyKzAwOjAwGNnmGwAAACV0RVh0ZGF0ZTptb2RpZnkAMjAyNi0w'
    b'NS0xNFQyMjoxNTozOSswMDowMN+vqeIAAAAodEVYdGRhdGU6dGltZXN0YW1wADIwMjYtMDUt'
    b'MTRUMjM6MDQ6MDErMDA6MDDGAKzCAAAAX0lEQVRIx+3PsQ2AMAxE0R+RjgXYiT0QM9DDDOzB'
    b'UgyQksgUCVBbINHcq31fMojIJwKsL+YjsWY6Wuc2sQM10LDQczjmkY2BfAXAMMwRuK9LIDMx'
    b'uwKBRH4CVv4RkR+dudYSz+OsUh4AAAAASUVORK5CYII=')

#----------------------------------------------------------------------
Class = PyEmbeddedImage(
    b'iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAQAAADZc7J/AAAAAmJLR0QA/4ePzL8AAAAJcEhZ'
    b'cwAALiMAAC4jAXilP3YAAAAHdElNRQfqBQ4XBAFZNipgAAAAJXRFWHRkYXRlOmNyZWF0ZQAy'
    b'MDI2LTA1LTE0VDIyOjU3OjMyKzAwOjAwGNnmGwAAACV0RVh0ZGF0ZTptb2RpZnkAMjAyNi0w'
    b'NS0xNFQyMjoxNTozOSswMDowMN+vqeIAAAAodEVYdGRhdGU6dGltZXN0YW1wADIwMjYtMDUt'
    b'MTRUMjM6MDQ6MDErMDA6MDDGAKzCAAABVklEQVRIx92Uu0oDQRSG/9lLLnvBiJCACCoEBPER'
    b'fBBbC5/AV7DxCcTGwlZ8A8ugWFiJ2qSwCoiQBGNM9jJz7HQncs4qqeJfze7O/zHnnH8HWHip'
    b'72XnD7bdr5U3g3NKvQRTfLQBFUQeKclNeQ0J+gygpp90ckirIK5g1WuervjFzxYgoKye76Et'
    b'tKybnDup5gAGipwRTe0qC3LUmzL28SzAyAkHHwcI+RLwvjQ0PgvQ2Mwe7jg3ANQQxMQDgATt'
    b'wox/qoPZIZXPvURzA7zZF0NcCttTVEgE5Mh9V4hi37SU4gEh3TfSY1oXcvDsHTUTwwEyuKlz'
    b'Q10B8OqnQpBStT2+PePcABCgEVMo9GCsdmjhcwBczQMIcA0tbI+xRcIUqvQY1fepyf/O9DK4'
    b'WDbsjaQAFy2s8TmAMq6NtwDTykbknsg16ypN+B5M0NMolXCtE37h/3f6BEHVcvel6JliAAAA'
    b'AElFTkSuQmCC')

#----------------------------------------------------------------------
Composition = PyEmbeddedImage(
    b'iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAQAAADZc7J/AAAAOGVYSWZNTQAqAAAACAABh2kA'
    b'BAAAAAEAAAAaAAAAAAACoAIABAAAAAEAAAhWoAMABAAAAAEAAAhWAAAAAMFeALwAAAACYktH'
    b'RAD/h4/MvwAAAAd0SU1FB+oFDhcEAVk2KmAAAAAldEVYdGRhdGU6Y3JlYXRlADIwMjYtMDUt'
    b'MTRUMjI6NTc6MzIrMDA6MDAY2eYbAAAAJXRFWHRkYXRlOm1vZGlmeQAyMDI2LTA1LTE0VDIy'
    b'OjU3OjA2KzAwOjAwE0R9VwAAACh0RVh0ZGF0ZTp0aW1lc3RhbXAAMjAyNi0wNS0xNFQyMzow'
    b'NDowMSswMDowMMYArMIAAAASdEVYdGV4aWY6RXhpZk9mZnNldAAyNlMbomUAAAAZdEVYdGV4'
    b'aWY6UGl4ZWxYRGltZW5zaW9uADIxMzT4qaKHAAAAGXRFWHRleGlmOlBpeGVsWURpbWVuc2lv'
    b'bgAyMTM0QVJ5bwAAAD10RVh0aWNjOmNvcHlyaWdodABDb3B5cmlnaHQgMjAwNyBBcHBsZSBJ'
    b'bmMuLCBhbGwgcmlnaHRzIHJlc2VydmVkLp5m3CkAAAAjdEVYdGljYzpkZXNjcmlwdGlvbgBH'
    b'ZW5lcmljIFJHQiBQcm9maWxlGqc4jgAAAPJJREFUSMftk70OAUEUhb9dlOIJREGlRnSikeg8'
    b'xIYoRO8pRMnWSko/neg8g8ZPoUS2EcmsZrHDihtR7mkmM3PPlzNzcyFUKDD8m4m31rj8Apho'
    b'F1UhwHyxF2iTfMd9BXjlZYZ0sUnJEYZmH5AGYE6djewhkQA7pMmyXJ0sQYIo73aACv1zh6Pe'
    b'JU0OhycgSU+zA2Ylnotdrp8AUUY0Uc8EbkCRixt4DqBQ/ifsaGGT0SqmTud6ND8lMHBQoB4J'
    b'FlgaYkYjsRX8odbG0gMxo84WJG00fWULLNbAVG73zYKXIk+RMXup/Q/DFDjOUnOoUHfdAD5d'
    b'PvRARJMhAAAAAElFTkSuQmCC')

#----------------------------------------------------------------------
Inheritance = PyEmbeddedImage(
    b'iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAQAAADZc7J/AAAAAmJLR0QA/4ePzL8AAAAJcEhZ'
    b'cwAALiMAAC4jAXilP3YAAAAHdElNRQfqBQ4XBAFZNipgAAAAJXRFWHRkYXRlOmNyZWF0ZQAy'
    b'MDI2LTA1LTE0VDIyOjU3OjMyKzAwOjAwGNnmGwAAACV0RVh0ZGF0ZTptb2RpZnkAMjAyNi0w'
    b'NS0xNFQyMjoxNTozOSswMDowMN+vqeIAAAAodEVYdGRhdGU6dGltZXN0YW1wADIwMjYtMDUt'
    b'MTRUMjM6MDQ6MDErMDA6MDDGAKzCAAABXUlEQVRIx+2TO0gDQRRF79tdPyQIiabwBzZC0MJO'
    b'tFMLe0vBLkRIIZLSJp0giI3dFiIECxMrtRLBXyGIhaCFIIKNCgEVNBa64s61SNaENZss1nur'
    b'mTfzDof5AEGCANJ4i/k7Sv0HYLrmbojmw1LDNDKIS02gDwO2a5vag+rlCTZw7/bwY6DD0heb'
    b'0npM1jDHWAnrmMhfKXcY1bJGGnejcjZsJ9nNLW5L0TExAABdGPJ0oUTRBgKX5HnkojimEpxi'
    b'FnuwAJQBE7KgXXkqhNgBAmF8wfpWB6HTz0k1r+KyzKozIOhl4AxaoZyCQJx6yeCQT7buCYhI'
    b'CgI8w0bYsMY/EmzmKvZZBSigUO8QZQYC9MnNyFuSncxxR96dVaP2A63EBAxAyMHrWQ5wl3l5'
    b'kfINVAzqx0aLnVE9PMIKHqubfQLklet2P5bklq5mvwYKeec6jpFz4xv31//OQYIAwA8otHXH'
    b'r3fsugAAAABJRU5ErkJggg==')

#----------------------------------------------------------------------
NewClassDiagram = PyEmbeddedImage(
    b'iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAQAAADZc7J/AAAAOGVYSWZNTQAqAAAACAABh2kA'
    b'BAAAAAEAAAAaAAAAAAACoAIABAAAAAEAAAhWoAMABAAAAAEAAAhWAAAAAMFeALwAAAACYktH'
    b'RAD/h4/MvwAAAAd0SU1FB+oFDhcEAVk2KmAAAAAldEVYdGRhdGU6Y3JlYXRlADIwMjYtMDUt'
    b'MTRUMjI6NTc6MzIrMDA6MDAY2eYbAAAAJXRFWHRkYXRlOm1vZGlmeQAyMDI2LTA1LTE0VDIy'
    b'OjQyOjI0KzAwOjAw4Vl/hwAAACh0RVh0ZGF0ZTp0aW1lc3RhbXAAMjAyNi0wNS0xNFQyMzow'
    b'NDowMSswMDowMMYArMIAAAASdEVYdGV4aWY6RXhpZk9mZnNldAAyNlMbomUAAAAZdEVYdGV4'
    b'aWY6UGl4ZWxYRGltZW5zaW9uADIxMzT4qaKHAAAAGXRFWHRleGlmOlBpeGVsWURpbWVuc2lv'
    b'bgAyMTM0QVJ5bwAAAD10RVh0aWNjOmNvcHlyaWdodABDb3B5cmlnaHQgMjAwNyBBcHBsZSBJ'
    b'bmMuLCBhbGwgcmlnaHRzIHJlc2VydmVkLp5m3CkAAAAjdEVYdGljYzpkZXNjcmlwdGlvbgBH'
    b'ZW5lcmljIFJHQiBQcm9maWxlGqc4jgAAAddJREFUSMfdkr9rFEEUxz8zt/fDeLkYlAtXhQQu'
    b'gRQiGNIEtIiFJgTMFTGVYJFCGwubFCE2KUIgIAHJP2ApglqkMcUhFoKIgq1yanEENMTkvJ+7'
    b'MxZnwu3ezuy1+qp9b+d95n2/b+CfDxEs7AbyGlkestcr4G977KSumHUHqXDViHBCagvcRrY/'
    b'pXzw4XAzflxkxoBwQip3mD9JJN/nGHRW3IoJITuTJK+4roSvpgR3GxtOWlBkJgog2ZLn5r7m'
    b'A8ZIZUH4AA3IVbfKY7LrlBnhHxeSuq9rs1ZE12XozkSQ60DUNlrpS8xGbMFH11yhzEc8ACnu'
    b'XXBvrezXewRo3vGGJhPcJNUeTOhC4tFoyS7h9MdrtlGc5xkvOEuGDBkGSJHqRYKgykumWcZh'
    b'grf8pt9vTrSEIw64SAyXKSYRhnaLhBiSJgKByy+UxWiDgQMMU+SAJs/Zpo4wAIwSEizymDXO'
    b'8IMl0kYJRoBinFU+0WCMEWN7xDvIcg3QFgciXqJuv0BrdJkojHadHrBPoKgZVqPQUKdhAQjw'
    b'PJ7yLQQh9dSTfMl7z75loAQi2bqvpkNck3xhff3nZQBumABxoMVQiLGaRXcHj91AewBQYA+B'
    b'DLVR4ZLlM/9h/AHlz4l/Ycb1JgAAAABJRU5ErkJggg==')

#----------------------------------------------------------------------
NewProject = PyEmbeddedImage(
    b'iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAQAAADZc7J/AAAAOGVYSWZNTQAqAAAACAABh2kA'
    b'BAAAAAEAAAAaAAAAAAACoAIABAAAAAEAAAhWoAMABAAAAAEAAAhWAAAAAMFeALwAAAACYktH'
    b'RAD/h4/MvwAAAAd0SU1FB+oFDhcEAVk2KmAAAAAldEVYdGRhdGU6Y3JlYXRlADIwMjYtMDUt'
    b'MTRUMjI6NTc6MzIrMDA6MDAY2eYbAAAAJXRFWHRkYXRlOm1vZGlmeQAyMDI2LTA1LTE0VDIy'
    b'OjUwOjAxKzAwOjAwND9YoAAAACh0RVh0ZGF0ZTp0aW1lc3RhbXAAMjAyNi0wNS0xNFQyMzow'
    b'NDowMSswMDowMMYArMIAAAASdEVYdGV4aWY6RXhpZk9mZnNldAAyNlMbomUAAAAZdEVYdGV4'
    b'aWY6UGl4ZWxYRGltZW5zaW9uADIxMzT4qaKHAAAAGXRFWHRleGlmOlBpeGVsWURpbWVuc2lv'
    b'bgAyMTM0QVJ5bwAAAD10RVh0aWNjOmNvcHlyaWdodABDb3B5cmlnaHQgMjAwNyBBcHBsZSBJ'
    b'bmMuLCBhbGwgcmlnaHRzIHJlc2VydmVkLp5m3CkAAAAjdEVYdGljYzpkZXNjcmlwdGlvbgBH'
    b'ZW5lcmljIFJHQiBQcm9maWxlGqc4jgAAAftJREFUSMfdlU1rE1EUhp+b3EkbmsSEiVZNUqFF'
    b'SoxZuLCFuhI/69aF64KuBFfaVZfudNcfUBA39g+IblUQRXAhVmlo4gc0xcZQq9bJfFwX1clM'
    b'MhnadKV3NXM457nve+bOufDPL+F/fbjDsulgwJ9yGVpro7wIT/IACzyIPL7mTHfq8imuc4fl'
    b'dsAFHGeZxVjt5M3rqbLq9gawvTV85HYAQGDBRCyvxQUKk42/6W5xnOT2Y8Ib9wAUxHPffv1s'
    b'VnP5J9q9jt0dRrlFAoWf7AIsJK0Xb8/KWiN5I/MlvdZlQGL4N/cDJIBS9sXD6aMyFdSBSGBX'
    b'PQALJsdb+n65r0Ola0KEAQQCthr6Ur1pTI2UB893QBwKDAWAZTtBYj83Tq9sfB2csEoc60oV'
    b'gbpcQIE3cLAxfOqAXnJkUGpQzNOZGhaUz33WddX7HIb3IIq9+uyEVllvXhmTQzsFuAo0NJzX'
    b'mUpGjAyIaB8KbExEqThWzKbH7V1YiLQBFhy5UE0mtr736Fc4II4GS49G77+bf9/a7MtCFPND'
    b'tjqVig5r8T4AYCImjdyhbCLfVw8cHFSyuO44q2tqFwQXYKLBq5f64srCJ/NHaI3voLkWZphl'
    b'tnHmqTHXKsQSoYDNHrSrXAbJjLikRM8PKahzl0p7KgeN9Shhf0PHWN/zxfIfrN+DkJVs3gkW'
    b'0AAAAABJRU5ErkJggg==')

#----------------------------------------------------------------------
NewSequenceDiagram = PyEmbeddedImage(
    b'iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAQAAADZc7J/AAAAOGVYSWZNTQAqAAAACAABh2kA'
    b'BAAAAAEAAAAaAAAAAAACoAIABAAAAAEAAAhWoAMABAAAAAEAAAhWAAAAAMFeALwAAAACYktH'
    b'RAD/h4/MvwAAAAd0SU1FB+oFDhcEAVk2KmAAAAAldEVYdGRhdGU6Y3JlYXRlADIwMjYtMDUt'
    b'MTRUMjI6NTc6MzIrMDA6MDAY2eYbAAAAJXRFWHRkYXRlOm1vZGlmeQAyMDI2LTA1LTE0VDIy'
    b'OjQ2OjM3KzAwOjAwFfDF/gAAACh0RVh0ZGF0ZTp0aW1lc3RhbXAAMjAyNi0wNS0xNFQyMzow'
    b'NDowMSswMDowMMYArMIAAAASdEVYdGV4aWY6RXhpZk9mZnNldAAyNlMbomUAAAAZdEVYdGV4'
    b'aWY6UGl4ZWxYRGltZW5zaW9uADIxMzT4qaKHAAAAGXRFWHRleGlmOlBpeGVsWURpbWVuc2lv'
    b'bgAyMTM0QVJ5bwAAAD10RVh0aWNjOmNvcHlyaWdodABDb3B5cmlnaHQgMjAwNyBBcHBsZSBJ'
    b'bmMuLCBhbGwgcmlnaHRzIHJlc2VydmVkLp5m3CkAAAAjdEVYdGljYzpkZXNjcmlwdGlvbgBH'
    b'ZW5lcmljIFJHQiBQcm9maWxlGqc4jgAAAdRJREFUSMfdkz9IW1EUh797jUaijQrBEigUCgou'
    b'IlSKIOiggn9aSqVYXIQOHeri4CI4uDiIIIgg7ebi6ObgoA6Ci4vNIDqIJW1pQyi1omIMee9e'
    b'BxPIe3n3Jri1Z7rncH/fPed33oN/PoS/sOXLMzQzx26lgLy8qlBXDDtNXNNrRIQCam+YQN4f'
    b'pZxOXCxWX+3RZ0CEAirveVVIJD9GaArNONcmhCxOwuwwqISnpgQfswuhesEefeUAkiXZOPKt'
    b'xWeMVBaEB5CF+M1SqlWW3DIjvO1CWEdKNmtFlDyGLk4E8SJEZiFX38FwmS0UiQWKXlIkUABS'
    b'TMacdzPp24oAgnO2SRJjgPF7AAg9WrP8LGkfIR851jiglZ98RtNAlChRGqiltpIRBFnO6OQ1'
    b'/Zwg0V5rygM0EQbZ5JQ2+qkzyq0eDNHBMft8YZaYESFN8r+scslL3pLmN8L0jnmEOgQrPOUX'
    b'bTx5yAhhPnBEih7aefQQgCZCFwDKIrd+iRqX8lFiorAYlr9g70CRMaxGoeGWrAUgwHXZ4HsA'
    b'QuoX6y1J95C0paEaRDg3pboL/45n1K/Mz/95DsCQCVAN5HgcYKxmzPmEy5ZP7gOMsotABtqo'
    b'cGjmjP8w7gAS8ohUl6z8EwAAAABJRU5ErkJggg==')

#----------------------------------------------------------------------
NewUseCaseDiagram = PyEmbeddedImage(
    b'iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAQAAADZc7J/AAAAOGVYSWZNTQAqAAAACAABh2kA'
    b'BAAAAAEAAAAaAAAAAAACoAIABAAAAAEAAAhWoAMABAAAAAEAAAhWAAAAAMFeALwAAAACYktH'
    b'RAD/h4/MvwAAAAd0SU1FB+oFDhcEAVk2KmAAAAAldEVYdGRhdGU6Y3JlYXRlADIwMjYtMDUt'
    b'MTRUMjI6NTc6MzIrMDA6MDAY2eYbAAAAJXRFWHRkYXRlOm1vZGlmeQAyMDI2LTA1LTE0VDIy'
    b'OjQ2OjM3KzAwOjAwFfDF/gAAACh0RVh0ZGF0ZTp0aW1lc3RhbXAAMjAyNi0wNS0xNFQyMzow'
    b'NDowMSswMDowMMYArMIAAAASdEVYdGV4aWY6RXhpZk9mZnNldAAyNlMbomUAAAAZdEVYdGV4'
    b'aWY6UGl4ZWxYRGltZW5zaW9uADIxMzT4qaKHAAAAGXRFWHRleGlmOlBpeGVsWURpbWVuc2lv'
    b'bgAyMTM0QVJ5bwAAAD10RVh0aWNjOmNvcHlyaWdodABDb3B5cmlnaHQgMjAwNyBBcHBsZSBJ'
    b'bmMuLCBhbGwgcmlnaHRzIHJlc2VydmVkLp5m3CkAAAAjdEVYdGljYzpkZXNjcmlwdGlvbgBH'
    b'ZW5lcmljIFJHQiBQcm9maWxlGqc4jgAAAbhJREFUSMfdk79LW1EUxz/35sWENiQGxBLo5K+h'
    b'YBEEBwUdHFoNDjrUreCoDh26ONUlQygE3JzcHLt1yGJA/wEpThmaGi1UHAoFY2PIe/c6mEDy'
    b'3rs3cdQzvXPe+37OOd/Dgycfwl8o+vI6w+xS6hfQkkfadcWym6bGghHhhNRW+Yh8eJTy849/'
    b'X6M3JywaEE5IZYOVdiL5nSXt7Lg1E0J2JjGOeK9EV00JNht5JyE4YbEXQFKQg9mLcZ8xUlkQ'
    b'XYAGZP4XriZk4CszontciOkXgctaEYFm6M5EkOlA1PPNxBTLPa7QIQbFPH84wwOQYmvIXd+5'
    b'vusL0OQ7E7wlxSQp3j2MKvTawN5I1b5Cq7vLMRUEgjJnJEiSJEmKOPF+V4i06ALpt6b3BP2H'
    b'BaBp/2vaAnBMYoeX/OQWl3OSlj5GD2JkOeALHjW2iaAeC1DMkqFMhDe8NsqtV4BRxgBtkfcA'
    b'2ITtCLgjEHaF73VgAkXd4LlCwx0NC0CA5/GNyxCE1DOH41XvlGvLQAOIWPOTmgtZXvKLXO7v'
    b'NABLJkAUaPIqxFjNB3cfj6JP7gOsUUIgQ21UuAxT4RnGPRfYeU/DU2EwAAAAAElFTkSuQmCC')

#----------------------------------------------------------------------
Note = PyEmbeddedImage(
    b'iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAQAAADZc7J/AAAAOGVYSWZNTQAqAAAACAABh2kA'
    b'BAAAAAEAAAAaAAAAAAACoAIABAAAAAEAAAhWoAMABAAAAAEAAAhWAAAAAMFeALwAAAACYktH'
    b'RAD/h4/MvwAAAAd0SU1FB+oFDhcEAVk2KmAAAAAldEVYdGRhdGU6Y3JlYXRlADIwMjYtMDUt'
    b'MTRUMjI6NTc6MzIrMDA6MDAY2eYbAAAAJXRFWHRkYXRlOm1vZGlmeQAyMDI2LTA1LTE0VDIy'
    b'OjUwOjAxKzAwOjAwND9YoAAAACh0RVh0ZGF0ZTp0aW1lc3RhbXAAMjAyNi0wNS0xNFQyMzow'
    b'NDowMSswMDowMMYArMIAAAASdEVYdGV4aWY6RXhpZk9mZnNldAAyNlMbomUAAAAZdEVYdGV4'
    b'aWY6UGl4ZWxYRGltZW5zaW9uADIxMzT4qaKHAAAAGXRFWHRleGlmOlBpeGVsWURpbWVuc2lv'
    b'bgAyMTM0QVJ5bwAAAD10RVh0aWNjOmNvcHlyaWdodABDb3B5cmlnaHQgMjAwNyBBcHBsZSBJ'
    b'bmMuLCBhbGwgcmlnaHRzIHJlc2VydmVkLp5m3CkAAAAjdEVYdGljYzpkZXNjcmlwdGlvbgBH'
    b'ZW5lcmljIFJHQiBQcm9maWxlGqc4jgAAAYJJREFUSMfdlbFKw1AUhr+bJthiKTooIraIi6BC'
    b'hyKCS+dQfIKiIAq+iYsv0MlHcBCxo5ODSBeXTuIiLVpdFCqUJnGoaZrcc2tWPdPNIfc7/3/u'
    b'yQ38+VDRsplqg5t4thPbnUlkInyGetKOPe1xgmXU2ueU1nSASw0sQYRPAHDzGwAIeORDK15i'
    b'ngDJnq2nBnxpAG+8jlrtygDFhlDIG1mIRRNXAvi0eEkgFGWWQ0SJQzzO6RgsKFZZ0nJzkYID'
    b'nnGoc2YEFJjV5DrRMsc1DkdY+CLA556uZmGbYqjBJ4MVCdIAFjtCwzJCzgAIeKOvncMCeQNC'
    b'mIMur9o8Z8nHq5gtKCrC5+CNOpbOwgPvWhPXWUxvoaApUMxgCsFCUXwx9Sn43NGZNgcJnjAH'
    b'ZTa1Orn0CmDIwNQDBT8NUjLAA5+2MMoVVghgC4sreuzyGZ5rHHDLsZWVRlmNcnWeuKRKjYas'
    b'4IIMVWzjxaxYY58eDdpRahzp/guhmPBKixVLiZjY/i/iG0NeWTrECJDpAAAAAElFTkSuQmCC')

#----------------------------------------------------------------------
NoteAssociation = PyEmbeddedImage(
    b'iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAQAAADZc7J/AAAAOGVYSWZNTQAqAAAACAABh2kA'
    b'BAAAAAEAAAAaAAAAAAACoAIABAAAAAEAAAhWoAMABAAAAAEAAAhWAAAAAMFeALwAAAACYktH'
    b'RAD/h4/MvwAAAAd0SU1FB+oFDhcEAVk2KmAAAAAldEVYdGRhdGU6Y3JlYXRlADIwMjYtMDUt'
    b'MTRUMjM6MDM6MDUrMDA6MDD22wrLAAAAJXRFWHRkYXRlOm1vZGlmeQAyMDI2LTA1LTE0VDIz'
    b'OjAxOjM1KzAwOjAwDfxlqQAAACh0RVh0ZGF0ZTp0aW1lc3RhbXAAMjAyNi0wNS0xNFQyMzow'
    b'NDowMSswMDowMMYArMIAAAASdEVYdGV4aWY6RXhpZk9mZnNldAAyNlMbomUAAAAZdEVYdGV4'
    b'aWY6UGl4ZWxYRGltZW5zaW9uADIxMzT4qaKHAAAAGXRFWHRleGlmOlBpeGVsWURpbWVuc2lv'
    b'bgAyMTM0QVJ5bwAAAD10RVh0aWNjOmNvcHlyaWdodABDb3B5cmlnaHQgMjAwNyBBcHBsZSBJ'
    b'bmMuLCBhbGwgcmlnaHRzIHJlc2VydmVkLp5m3CkAAAAjdEVYdGljYzpkZXNjcmlwdGlvbgBH'
    b'ZW5lcmljIFJHQiBQcm9maWxlGqc4jgAAAINJREFUSMft0DEOwVAcx/GPBrOVK4gDmIy4gRgZ'
    b'eiVh6gHEKHGFHsBEHIFdW0sjr7MOhvdZvvkNL/nnEUVRKzrNeUZiXq+rBwam9b4osGg8Sn69'
    b'oFt3aeYotzKRudkaOnhK9e30pF72RjbuMmNruVN4QemtCloo+LYKWgb9iz+IoqglH3PGKeAS'
    b'V9yIAAAAAElFTkSuQmCC')

#----------------------------------------------------------------------
OpenProject = PyEmbeddedImage(
    b'iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAQAAADZc7J/AAAAOGVYSWZNTQAqAAAACAABh2kA'
    b'BAAAAAEAAAAaAAAAAAACoAIABAAAAAEAAAhWoAMABAAAAAEAAAhWAAAAAMFeALwAAAACYktH'
    b'RAD/h4/MvwAAAAd0SU1FB+oFDhcEAVk2KmAAAAAldEVYdGRhdGU6Y3JlYXRlADIwMjYtMDUt'
    b'MTRUMjI6NTc6MzMrMDA6MDC+ru2vAAAAJXRFWHRkYXRlOm1vZGlmeQAyMDI2LTA1LTE0VDIy'
    b'OjUwOjAxKzAwOjAwND9YoAAAACh0RVh0ZGF0ZTp0aW1lc3RhbXAAMjAyNi0wNS0xNFQyMzow'
    b'NDowMSswMDowMMYArMIAAAASdEVYdGV4aWY6RXhpZk9mZnNldAAyNlMbomUAAAAZdEVYdGV4'
    b'aWY6UGl4ZWxYRGltZW5zaW9uADIxMzT4qaKHAAAAGXRFWHRleGlmOlBpeGVsWURpbWVuc2lv'
    b'bgAyMTM0QVJ5bwAAAD10RVh0aWNjOmNvcHlyaWdodABDb3B5cmlnaHQgMjAwNyBBcHBsZSBJ'
    b'bmMuLCBhbGwgcmlnaHRzIHJlc2VydmVkLp5m3CkAAAAjdEVYdGljYzpkZXNjcmlwdGlvbgBH'
    b'ZW5lcmljIFJHQiBQcm9maWxlGqc4jgAAAcJJREFUSMfllL9rFEEUxz9vbtWLepcUslFQOCRF'
    b'QLAQREGCnXhNLAT9CyytBCsLWxsb/wELCwUl5clFkHRa2GgViKIEm1y0OD2N7O17Nvdjdnfu'
    b'sleKb5uZnZnP+37fvln450OGg1ZgsVkC4ArA4TMBOk1BzG1OY4P3azwvoyLyxte5581W2Obt'
    b'ZBXNAOBYZscpHnCL3bHGkeIee2EFlktyWdb5mQNgxkfushkCAOmHP53RESmUGOxQXFllYwLA'
    b'6avXD89Gc0XHKpZiiP66076yrEfCFhDr1u1CUgSkiy/PfDcHJCd2eMqXCQBz8VeeRNVcduKt'
    b'R+cXVk0BUac7PC4AWgAivd05LvYPZ8472bzfq1/tj1PVOUc7pOC9PrukC++ypVNOSuOmZotd'
    b'CVs4aDfi2qJmDQjq8t/XDx+wTM0wx0wx2N6EYiOVilwjSabxrAQz2wd8s21v1mBe9kPkFCR0'
    b'PXfp7BYUs6ELtf6++TMA4TdvUvXuUpuVSkO0LAAS9mwpGgIcn62bv81TARKhfErHCn5QrcxQ'
    b'ROtUuXYg8RYdRwka6IQVvJDjtSW/bsE+ELZY86eDaOXmU8Ig/FMdLf5n8Rf5toReYHDnhAAA'
    b'AABJRU5ErkJggg==')

#----------------------------------------------------------------------
Pointer = PyEmbeddedImage(
    b'iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAQAAADZc7J/AAAAOGVYSWZNTQAqAAAACAABh2kA'
    b'BAAAAAEAAAAaAAAAAAACoAIABAAAAAEAAAhWoAMABAAAAAEAAAhWAAAAAMFeALwAAAACYktH'
    b'RAD/h4/MvwAAAAd0SU1FB+oFDhcEAVk2KmAAAAAldEVYdGRhdGU6Y3JlYXRlADIwMjYtMDUt'
    b'MTRUMjI6NTc6MzMrMDA6MDC+ru2vAAAAJXRFWHRkYXRlOm1vZGlmeQAyMDI2LTA1LTE0VDIy'
    b'OjUwOjAxKzAwOjAwND9YoAAAACh0RVh0ZGF0ZTp0aW1lc3RhbXAAMjAyNi0wNS0xNFQyMzow'
    b'NDowMSswMDowMMYArMIAAAASdEVYdGV4aWY6RXhpZk9mZnNldAAyNlMbomUAAAAZdEVYdGV4'
    b'aWY6UGl4ZWxYRGltZW5zaW9uADIxMzT4qaKHAAAAGXRFWHRleGlmOlBpeGVsWURpbWVuc2lv'
    b'bgAyMTM0QVJ5bwAAAD10RVh0aWNjOmNvcHlyaWdodABDb3B5cmlnaHQgMjAwNyBBcHBsZSBJ'
    b'bmMuLCBhbGwgcmlnaHRzIHJlc2VydmVkLp5m3CkAAAAjdEVYdGljYzpkZXNjcmlwdGlvbgBH'
    b'ZW5lcmljIFJHQiBQcm9maWxlGqc4jgAAAylJREFUSMfVkt9vk1UYxz/nvO27tnbtOzc3RtsB'
    b'G2xqmDh1ikzhBgcLMSNswRhjAjf4IwF3oVz5BxgvvDBOxUQNRiGaJSYaKiQLSBi/GljWyY+R'
    b'8aNskmXTrVvd1vVt3/d4QUdKV+J2h9+bc/I853ye5/meA/97ibvLAZYBCkHrEgEOgHW4OEUT'
    b'bhRhwEaQYsfiAVdJ4g8431BOot6B6pHdM/twE0bhwOTV/x7BR0LWfrb/nRCWOfzXzPWKaEmv'
    b'/1JprC5+2DYAsJBM89qDOrDxOAarIlQxpx8IXA9UbqpSKyeDQ5VXynr1vvSgPeqcUxQTZorX'
    b'8wAaQDnjFmVmywbcFKMzxTURcZ9edr4+2pzaWd0um6nHu2L4Wvp9ZgoBPKRgPNH6hBEiSCOb'
    b'2EgDARTDOB3PGbKGJqutO9nR8wnThZ/RYK3o+XLrnn3ZgEQAaf7BiQeQ/M7Xv4y1PZqZyAPI'
    b'u4vJGUVX38xINmBjYSExeAQQ9PPN7FgXGX2BiVnA87hwnxu9GJlvKSuFQhDnW3P049Ahb172'
    b'ngcQI03GxGe2bKBQFWOg/oMXJ59hL4cKA6ASM2tkELXg0IrS2qpgZNVUhjfzEHJ+M4KXl2/M'
    b'HushU+C72JpqF9+rBh0IFwZAilOKrr7ZkXtBef/ML4nDbHHkIXIA63HhOTd2Yd5IwSDx3ANQ'
    b'x0F7ly0hzM/5HsAt0qRN5TNbmtDRuMxHXKEOf64nXjZLwQUyTtr58X4ABEkixidbS4wAt/g8'
    b'fXv4jjHASspzETobRZlxdij5Nql8QAIfT8dvP9n/bISj3PnO9a7t//upqKgglOuGVI1/WG8d'
    b'7ySRDwDJENqE+cpEcfKIu8OKubptLdHY6/BQk2NtP53Jjp+kNbcQ8ALThP5MnBDH9M70qIUw'
    b'/SfNeHJ91J2hFh2FJMan1s0vOO1ltsCD46cUB5IioAYXHsDZRkyqZvWDOqoOqgbFV8UeN2Us'
    b'Sl58gN4kelFrVLOqVuJX12N6gQ//QJWwHCiqk7+hUJwtWq0BLYsHQAWg4SrX3tM+1GsBHl/K'
    b'dYAayDbtAJbnZMTiIdsBUGxjz1LrP9z6F2GaEeJ9BTZ7AAAAAElFTkSuQmCC')

#----------------------------------------------------------------------
Realization = PyEmbeddedImage(
    b'iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAQAAADZc7J/AAAAOGVYSWZNTQAqAAAACAABh2kA'
    b'BAAAAAEAAAAaAAAAAAACoAIABAAAAAEAAAhWoAMABAAAAAEAAAhWAAAAAMFeALwAAAACYktH'
    b'RAD/h4/MvwAAAAd0SU1FB+oFDhcEAVk2KmAAAAAldEVYdGRhdGU6Y3JlYXRlADIwMjYtMDUt'
    b'MTRUMjM6MDM6MTErMDA6MDDOPi5GAAAAJXRFWHRkYXRlOm1vZGlmeQAyMDI2LTA1LTE0VDIz'
    b'OjAxOjM1KzAwOjAwDfxlqQAAACh0RVh0ZGF0ZTp0aW1lc3RhbXAAMjAyNi0wNS0xNFQyMzow'
    b'NDowMSswMDowMMYArMIAAAASdEVYdGV4aWY6RXhpZk9mZnNldAAyNlMbomUAAAAZdEVYdGV4'
    b'aWY6UGl4ZWxYRGltZW5zaW9uADIxMzT4qaKHAAAAGXRFWHRleGlmOlBpeGVsWURpbWVuc2lv'
    b'bgAyMTM0QVJ5bwAAAD10RVh0aWNjOmNvcHlyaWdodABDb3B5cmlnaHQgMjAwNyBBcHBsZSBJ'
    b'bmMuLCBhbGwgcmlnaHRzIHJlc2VydmVkLp5m3CkAAAAjdEVYdGljYzpkZXNjcmlwdGlvbgBH'
    b'ZW5lcmljIFJHQiBQcm9maWxlGqc4jgAAAaZJREFUSMftkj1LW1EYx3/n3OvVmzRKIig4GIq2'
    b'gw6+JBFLAhXBFxqUDu3QLoqzH8MP4FLUwcnJbA5CQOiLX6BDCSlt0yqJLmojaX1J7s05HXop'
    b'IkqSzvktZ3ie5//8/w8HmjQBUU9TPwoXsPj2Pzt6vFdiYzF4q2rUFnjABWZUL2vHLSh9iWSB'
    b'j404CGFjrc7o6Jm1wQhIQvgacdCGn6v5V7EXdlekNF/sVodXZ4onnFOpT8DG4DoZjz2mn2gg'
    b'GD9PFgP6IF/SKLoxnvPZs6LvEbhGUk0mYr0ofAwyGvRP/pz6ZajvXF5gDJDFekpH9YSXTJDD'
    b'ZomHZBlgEcgzy1ylYMQTY2E0oGlniOEu8azwyNltrUgBCC117Sg30WhQoDFdoLwPJm7Kq74B'
    b'IEMGgDTpAGX5tyQQHLHHh0/H62zzu4K54025924LYlEGBJIT3vE292OTLQotOAQx6zEsAEmJ'
    b'9+wdf9lSm3w1WSCFQ7Ge8RBtWKvTOnLassYQGHTib+RgYQRmRKyQwBAEsHnd2MXD/0L4aGX8'
    b'jng16cOhiontfbomTW7zB+CPeg0P+CVYAAAAAElFTkSuQmCC')

#----------------------------------------------------------------------
Redo = PyEmbeddedImage(
    b'iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAQAAADZc7J/AAAAAmJLR0QA/4ePzL8AAAAJcEhZ'
    b'cwAALiMAAC4jAXilP3YAAAAHdElNRQfqBQ4XBAFZNipgAAAAJXRFWHRkYXRlOmNyZWF0ZQAy'
    b'MDI2LTA1LTE0VDIyOjU3OjMzKzAwOjAwvq7trwAAACV0RVh0ZGF0ZTptb2RpZnkAMjAyNi0w'
    b'NS0xNFQyMjoxNTo0MCswMDowMEDy5SgAAAAodEVYdGRhdGU6dGltZXN0YW1wADIwMjYtMDUt'
    b'MTRUMjM6MDQ6MDErMDA6MDDGAKzCAAACTklEQVRIx9WUO2hTURyHv3PuI4+2QRKLllJa7eBS'
    b'FFeNgwgqCoJQEBcfpa2Du+DU2UlBKBQfoIN00SLioIuIAUGhWqiv4hAdmkB9tGmSNo9z/w5N'
    b'btMYa9Otv+XCOff7zu8ezj2w5aPWn05UnvF/vqE3tk6CBHs32WA7NgssI427qHXQlbRTRuOQ'
    b'J4f5W6LWQUFjESNDHptWgpTIUqhOxhsJfNgmRAiNR4lMyeTRHOdt2AsrCeTuLMcxuPTXCyq4'
    b'SxsOy2rpQOEekGeKo3be9QLGJeC22VErpCf5IfWCxEqjCCEWX+S6iOpf7aZbemWXdLGDqEQI'
    b'EyRIUt8PPzDzYfoBuw6PYcbTvXT2lA+nj8h+OiWypmWGcW7unJ73B9Wa8jFKMxm6zbB3RnoB'
    b'KJEnhAtAkedc1y89oxFcLlY2azVt8CFjHTPXZB+Q5DVvmGGOEU4Ck9xQE5IVFJpBH1oVaFoP'
    b'pj+fMLelg6+MqUfqm2dAUElmGVV3JbVSebjRQUpAi+NMbys/kT6eqiveRw0IDkX0IVn03lsU'
    b'CdTBfoMEQCiY9c5LH8/UkKRsPC5T5hYKeQU2QgsDDU6s/wlafYp4p5jlqqRAuASA5e/2II1T'
    b'FSjbW+phN2PmnYNiqDI8wP9S/Z3FEumgwISF+PhG4t8HSqkoSb4oAk3gNQJd1oYZFhUXmhfE'
    b'Aadg5/nuGNUUXtNgTzHwW6WdJvEawWMvMOv8PFe9uZoXxHBTLXOjlr05QZwYwWxwql1Cm22w'
    b'QFlkLuedbVJQs+kPsRDgdJOKLZ8/EDfIa7zN/cwAAAAASUVORK5CYII=')

#----------------------------------------------------------------------
SaveProject = PyEmbeddedImage(
    b'iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAQAAADZc7J/AAAAOGVYSWZNTQAqAAAACAABh2kA'
    b'BAAAAAEAAAAaAAAAAAACoAIABAAAAAEAAAhWoAMABAAAAAEAAAhWAAAAAMFeALwAAAACYktH'
    b'RAD/h4/MvwAAAAd0SU1FB+oFDhcEAVk2KmAAAAAldEVYdGRhdGU6Y3JlYXRlADIwMjYtMDUt'
    b'MTRUMjI6NTc6MzMrMDA6MDC+ru2vAAAAJXRFWHRkYXRlOm1vZGlmeQAyMDI2LTA1LTE0VDIy'
    b'OjQ0OjM4KzAwOjAw501lKgAAACh0RVh0ZGF0ZTp0aW1lc3RhbXAAMjAyNi0wNS0xNFQyMzow'
    b'NDowMSswMDowMMYArMIAAAASdEVYdGV4aWY6RXhpZk9mZnNldAAyNlMbomUAAAAZdEVYdGV4'
    b'aWY6UGl4ZWxYRGltZW5zaW9uADIxMzT4qaKHAAAAGXRFWHRleGlmOlBpeGVsWURpbWVuc2lv'
    b'bgAyMTM0QVJ5bwAAAD10RVh0aWNjOmNvcHlyaWdodABDb3B5cmlnaHQgMjAwNyBBcHBsZSBJ'
    b'bmMuLCBhbGwgcmlnaHRzIHJlc2VydmVkLp5m3CkAAAAjdEVYdGljYzpkZXNjcmlwdGlvbgBH'
    b'ZW5lcmljIFJHQiBQcm9maWxlGqc4jgAAAc1JREFUSMfdlD1LHFEUhp8zc3d1I1F3RYQNJkYJ'
    b'BItUCShYKESDjUWaFCEpQpqUaYJgbe9fsEplkcrCf6BIINlGVwZRsFiXWG32a3auxerOfpzZ'
    b'2TY51eXcd555z3vnDvzzJfeL/a6m9EgttrVeb62cjucMBoGAN/wyOZMzOfPbeGbJrJkr81F8'
    b'ME3pmurgFZskOWTX97OLTz4kxAKCj4fPU+dm38s7Xzhih3LowbQ5mOYtsMonN6ilx9L3WwW+'
    b'8Yfv2BX5yyQbpNimqo1gaQBDzDAbpMN2nXM8KgQjTAIuX1kId9sBkTlLp2yY8ViAdAHAae+F'
    b'x9GRQVs1KLW2EmxRIcO1qlQBQolj5O5FwhzCGXXl24h0YKnFhxMFkD5yGwewpHgWZYsqeepx'
    b'DhJMRQIqeNS6HKraM3LKIC+ZGDTEMWaU7oiSQASgqDpIMzUoIMPznp4wOriDMkXFwSNSgwJ8'
    b'yooDX5N2AprXxjLOnCJ9iL27l1YD1BEOOOc9LgV+9owgjJLllB+8YJmG5kAYIoWLZV4JERyq'
    b'GB6Q1EdIgLx2IclFn0/5MZ/BBI70AoCLYA+3wgkx5XOph3jMOwT1tMMxAUugA5o/1b7X+b+s'
    b'W/UWbTHBYOayAAAAAElFTkSuQmCC')

#----------------------------------------------------------------------
SequenceDiagramInstance = PyEmbeddedImage(
    b'iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAQAAADZc7J/AAAAOGVYSWZNTQAqAAAACAABh2kA'
    b'BAAAAAEAAAAaAAAAAAACoAIABAAAAAEAAAhWoAMABAAAAAEAAAhWAAAAAMFeALwAAAACYktH'
    b'RAD/h4/MvwAAAAd0SU1FB+oFDhcEAVk2KmAAAAAldEVYdGRhdGU6Y3JlYXRlADIwMjYtMDUt'
    b'MTRUMjM6MDM6MTgrMDA6MDBbpmuVAAAAJXRFWHRkYXRlOm1vZGlmeQAyMDI2LTA1LTE0VDIz'
    b'OjAxOjM1KzAwOjAwDfxlqQAAACh0RVh0ZGF0ZTp0aW1lc3RhbXAAMjAyNi0wNS0xNFQyMzow'
    b'NDowMSswMDowMMYArMIAAAASdEVYdGV4aWY6RXhpZk9mZnNldAAyNlMbomUAAAAZdEVYdGV4'
    b'aWY6UGl4ZWxYRGltZW5zaW9uADIxMzT4qaKHAAAAGXRFWHRleGlmOlBpeGVsWURpbWVuc2lv'
    b'bgAyMTM0QVJ5bwAAAD10RVh0aWNjOmNvcHlyaWdodABDb3B5cmlnaHQgMjAwNyBBcHBsZSBJ'
    b'bmMuLCBhbGwgcmlnaHRzIHJlc2VydmVkLp5m3CkAAAAjdEVYdGljYzpkZXNjcmlwdGlvbgBH'
    b'ZW5lcmljIFJHQiBQcm9maWxlGqc4jgAAAWJJREFUSMfVkjtKA1EUhr9zZyaQiKSMRUwhUewF'
    b'ewUtxCZtduAK1EIQEXyswB2kcQfBDbgAH03AQoKFEBPFRGbm2CQzk2SYUQeL/M099/Lf7zzu'
    b'hZmXjIKzX148HK722KnliR8yY6QYLMULT6KAPCf2qvjJmdXoHcd8xgDUMRultTk0seMPXkr+'
    b'aVhltALFLVBEMegQIxBEgo+g4EZzmOkuXVq8AYrSpj2EdWjhBuAEgOGefRooQpdzLugiKA0O'
    b'eJy2T7wCoBRZoYwADksYcgCUWWY+Zj4xgEWOsFEgzx6ChQI7bOP8BACQC0bnBJEhh8LUL4kC'
    b'BPPK+1iW8BVG+8HE3CIA6etlZ0Ejfsu73YL1pmdFXCJtGcRX8MW1jJV4Q9OB3tUmf1eFSobb'
    b'QIFCssGkAOrUkw12CqCfrQGw01KktVClmq2FXeAhyWClAFyeeM46h0yqUUs2pA0xs8z/p5h9'
    b'fQPXu1s+D+fwwAAAAABJRU5ErkJggg==')

#----------------------------------------------------------------------
SequenceDiagramMessage = PyEmbeddedImage(
    b'iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAQAAADZc7J/AAAAOGVYSWZNTQAqAAAACAABh2kA'
    b'BAAAAAEAAAAaAAAAAAACoAIABAAAAAEAAAhWoAMABAAAAAEAAAhWAAAAAMFeALwAAAACYktH'
    b'RAD/h4/MvwAAAAd0SU1FB+oFDhcEAVk2KmAAAAAldEVYdGRhdGU6Y3JlYXRlADIwMjYtMDUt'
    b'MTRUMjM6MDM6MjErMDA6MDBAsSmlAAAAJXRFWHRkYXRlOm1vZGlmeQAyMDI2LTA1LTE0VDIz'
    b'OjAxOjM1KzAwOjAwDfxlqQAAACh0RVh0ZGF0ZTp0aW1lc3RhbXAAMjAyNi0wNS0xNFQyMzow'
    b'NDowMSswMDowMMYArMIAAAASdEVYdGV4aWY6RXhpZk9mZnNldAAyNlMbomUAAAAZdEVYdGV4'
    b'aWY6UGl4ZWxYRGltZW5zaW9uADIxMzT4qaKHAAAAGXRFWHRleGlmOlBpeGVsWURpbWVuc2lv'
    b'bgAyMTM0QVJ5bwAAAD10RVh0aWNjOmNvcHlyaWdodABDb3B5cmlnaHQgMjAwNyBBcHBsZSBJ'
    b'bmMuLCBhbGwgcmlnaHRzIHJlc2VydmVkLp5m3CkAAAAjdEVYdGljYzpkZXNjcmlwdGlvbgBH'
    b'ZW5lcmljIFJHQiBQcm9maWxlGqc4jgAAAiVJREFUSMftk01IlFEUhp9z7/c3Dk4yillN2aIx'
    b'k0qljLBokZgQIYHQokXQSloEtWlR0b6ijatw46xq26YfoqiIdmELzdyYM4r5E1MzJjOl3/fd'
    b'FqOWkKTQLp/VORfel/cczoUNNvgH6KXCw8FHAI0BHGoAH4PGQmEj1JJbzaeVavYgttKgFQ6u'
    b'a0FCcPGUsiIkcSGCy6E/J5imSK4+6KG5+mXhtLkhB4Lz9tzsRU7IfjvNmS0p0zQ/5X8KTR5N'
    b'Jx9WulQSocyzrusHMuJtUyn5qG7LhNUjM7pdV8S003PZXDNNWfsujS6KSqLLWgXgUGS+K2wJ'
    b'56gKWkwT/aZBpk2MKetdR+57gIlynKvxC931jxZuhsksPzhLbGmEBibQW80xc0ve0yhFk2Ac'
    b'R70lZ+JBPFNYmNQdrYd34FDHwfKKI7mTuWiYHpg1WARo2Mwkai/lUilVMioFGZKsZCQjX2VM'
    b'QmJqF+1Hk7WEGKLspTle1pZvLxQZUMbHghAIuswlfMAsDyeLnYCyZPHRYEhwjup9fVdmH8pn'
    b'sEprsFLh69/EKwml25z65ZrmqXnTX7jjfFGwlCAcDAdXuxFBtZWiCFM858XweC/3mHahZDAE'
    b'+Kue6m5GQQmaLK94lhlJmRRpCx+PfMngbxhEvvGExzPD9/1ehjQJssyRX9tnqQPs7pqxSB8t'
    b'iGITZWxfm7REEgvbYye2EMWjcz3iEjYOFi42desXb/Cf8BPYi7GkO4b1PwAAAABJRU5ErkJg'
    b'gg==')

#----------------------------------------------------------------------
Text = PyEmbeddedImage(
    b'iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAQAAADZc7J/AAAAOGVYSWZNTQAqAAAACAABh2kA'
    b'BAAAAAEAAAAaAAAAAAACoAIABAAAAAEAAAhWoAMABAAAAAEAAAhWAAAAAMFeALwAAAACYktH'
    b'RAD/h4/MvwAAAAd0SU1FB+oFDhcEAVk2KmAAAAAldEVYdGRhdGU6Y3JlYXRlADIwMjYtMDUt'
    b'MTRUMjI6NTc6MzMrMDA6MDC+ru2vAAAAJXRFWHRkYXRlOm1vZGlmeQAyMDI2LTA1LTE0VDIy'
    b'OjQ3OjQ3KzAwOjAw8Pen2QAAACh0RVh0ZGF0ZTp0aW1lc3RhbXAAMjAyNi0wNS0xNFQyMzow'
    b'NDowMSswMDowMMYArMIAAAASdEVYdGV4aWY6RXhpZk9mZnNldAAyNlMbomUAAAAZdEVYdGV4'
    b'aWY6UGl4ZWxYRGltZW5zaW9uADIxMzT4qaKHAAAAGXRFWHRleGlmOlBpeGVsWURpbWVuc2lv'
    b'bgAyMTM0QVJ5bwAAAD10RVh0aWNjOmNvcHlyaWdodABDb3B5cmlnaHQgMjAwNyBBcHBsZSBJ'
    b'bmMuLCBhbGwgcmlnaHRzIHJlc2VydmVkLp5m3CkAAAAjdEVYdGljYzpkZXNjcmlwdGlvbgBH'
    b'ZW5lcmljIFJHQiBQcm9maWxlGqc4jgAAAeJJREFUSMfdlM9r1EAYhp+ZTDbdTdZucXepdktB'
    b'vAjKIgi1FjxVWHpSEA9ar4J/keBZEMRj8eBB/At0xZ/YgyCCsKvt2Z1JxkPXmEkko3jrN4fw'
    b'kuGd93sm+eDo1A0SFlHefYpjJFzNtTh89JmgMIShFvUGodU6IKXHtGgAArVm7tgh0hMhE2N1'
    b'33y2boIQcVw/CEcnvU1ovqKfhLftvp63BIBBbtqta1yvBLDFmEDKYx5dMZfs7qGW+ba+UueI'
    b'mKHzNSMjJnJ0h7OoMOv/aqGQWCB4zbhwnmWJbSY8I5vrHtuVW3HiXmDovBZIBuwUdFhnAHvs'
    b'OR0nrHPAOE/Q4WK9QUzPMWgiiOhi5wYJot6gS+xoSUDM6VwHlVtyDARveFWCOGLC8wLE0b9B'
    b'BMkqtwraA/GjA9HSZp0DXuYMvBDbLDsGTSQLLOcGsQ/iEpGjAyRN1v4e4lsHInT+F6JAsMoO'
    b'v39eVWcAHyoQN9jnRQHiRr1Bh4GjF5A0WckTtOoYWGCFE6UNGYucd5r6o4GAqTHv1Bk8I5GM'
    b'9xgjp3aeKh9pdM3Dxtag8qWVS/OF2dPwpv2uy4nCU+auHRJ4HFIxVvfMp9JQ7fKNgJQoSj09'
    b'SDv7URzreW3SIqGB8qwGbVpc5gjVT4sFkqmfOO4kAAAAAElFTkSuQmCC')

#----------------------------------------------------------------------
Undo = PyEmbeddedImage(
    b'iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAQAAADZc7J/AAAAAmJLR0QA/4ePzL8AAAAJcEhZ'
    b'cwAALiMAAC4jAXilP3YAAAAHdElNRQfqBQ4XBAFZNipgAAAAJXRFWHRkYXRlOmNyZWF0ZQAy'
    b'MDI2LTA1LTE0VDIyOjU3OjMzKzAwOjAwvq7trwAAACV0RVh0ZGF0ZTptb2RpZnkAMjAyNi0w'
    b'NS0xNFQyMjoxNTo0MCswMDowMEDy5SgAAAAodEVYdGRhdGU6dGltZXN0YW1wADIwMjYtMDUt'
    b'MTRUMjM6MDQ6MDErMDA6MDDGAKzCAAACU0lEQVRIx9XTu09TcRTA8e+5v/a2peWlGKMJxjgQ'
    b'DQrGIFMnSXQwYVIHIxpFCSTK4OI/4CZ/geLg5OBjMrqIYcABQzQQTQwxPgANAYoCpY/b3t/P'
    b'gVup0tbcTnqWX3JPzuee83vAfx9SPjXmrfGKQKBy8d8jULZUCFOHy5KPEX4VK6LUkMdFFYB4'
    b'ZaCoZZsYNlmS5KihjgR5TCEZLw08JIdinJ5wJmZE1pvTbw1EsBQNBBBcMqRwSyEeILBdHzL5'
    b'3KKTJKucgNPgvNZNRNCck1chEyFEjlVyfxIekMJqTJ/VF9hNljTrskaCeZmVT/JRzbYlpswz'
    b'rkWpJc3K74QHpIFxDh5mkDNEi36gZYUZeWONqNHsXD9j2xCWMZuEt4n3yCBorIDu4jrHvON1'
    b'cIigACPT1n11l7mWehTLm10UHeMwLmCQOnOaQdqAp9xkJy100kkzyIS6kXpxpIkMyRIAwG00'
    b'gkGazWX6ecBVACtg9plTXGGvfFUXe5+/3MESuiSwgRzgHQ52h8T0qI2DhcFgtZlbHJfJYHfr'
    b'Ws5hfQOwtgJ9fEAIw4QeFTQDhBAUZkp6GTHtbk9NmnDh8pV9jcNeOsh5AO6QR6CDJzJTf3KP'
    b'6IWNXajwnLeOBlmCQ9Jrd7V+cZYx8dIjlIs+DEF4hGN2KVN4Hz4ACCLwns/SuNm4L+ASAqtM'
    b'i7byVQEg2C4zwZTtFC6Sb0Ah86Hv+50qOzAMEEyE5h/rwpeAP0AxpKKL9rdaqgTCxAhPhpMN'
    b'tFc3Qjc/XLOQN2tFPfmKo8SADCf8lf3b8RMSjcfB6DGurwAAAABJRU5ErkJggg==')

#----------------------------------------------------------------------
UseCase = PyEmbeddedImage(
    b'iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAQAAADZc7J/AAAAAmJLR0QA/4ePzL8AAAAJcEhZ'
    b'cwAALiMAAC4jAXilP3YAAAAHdElNRQfqBQ4XBAFZNipgAAAAJXRFWHRkYXRlOmNyZWF0ZQAy'
    b'MDI2LTA1LTE0VDIyOjU3OjMzKzAwOjAwvq7trwAAACV0RVh0ZGF0ZTptb2RpZnkAMjAyNi0w'
    b'NS0xNFQyMjoxNTo0MCswMDowMEDy5SgAAAAodEVYdGRhdGU6dGltZXN0YW1wADIwMjYtMDUt'
    b'MTRUMjM6MDQ6MDErMDA6MDDGAKzCAAAC50lEQVRIx92VSWgTURjHf28ypo2dxrSuMUq1hYpV'
    b'43JQrB5cwIpWD1L04IJ4ihU8WDxoFRSkKric1FxEPKhYBEGq1BUFKyiI0Lj2YG3BxC1NmzSm'
    b'WWaeh6RtpkvqVb/jN+/343uP/3sD/3yJkdveEXqevxN4yV2eXIIB2EoJ8yjHRSEQ4SttvKOD'
    b'xHCJGAZPZD01LMVpkkv8vOIWzXSZJcKEq2yijuUoIiRa8Yl2EQZpl7NxywWyCIMXnKWJ1KBC'
    b'ZOEODlNLgfgirlluWz+2RZ0ogEEn87TEHGOLsV2WEOUCDfT0KywA1Wn8PPtQlRuq5+fNgoAl'
    b'WYpgJkVIyuhL6IHvTxyPZLFcxEqm8Iw4NKUn8KaHb+AgKcuZ/BPxqJ04LtZkHcFjAuTRQ54W'
    b'O2LUoXKaenTwoGRWrMMDyhXb8WRUkM9OEw5r2YENQbLXdly5CtSyLv0lLbCxl0LxYdzJeJ/E'
    b'xeYRE1DNVAwSMbVBfKIQD/kAiheggkpQGrvbZzGD9aOGqJrpuAh+VhqBFcwFb2YCN8Xit/JU'
    b'4xtVOXO4gRAOxFMRYyLuwS1MB8IiYGEGY9VkVCwBIhlq4BAzpY8p0E357Rf4Abvh1Pk5piBI'
    b'Cn0ahRkqI2ilS46Xq0MUcy8nfocJhDFWSRtBWgEUD8B7WsDYNqm0kwBNo+K3+cU3isrkNuA5'
    b'HwaDFOMSETkndciaL/jOnVHwIGC1peplOWG89GUf4gMugrE7dkzVJEmu89AEN3ONFKBqsWPG'
    b'LuBC/4LB2ziBc+zBUBrVhte+xVix08sUJD/QiJDAh3uBXm9sRXCZA4SH3sY4zxAskUuMaudU'
    b'pdsSbklo9NBNH29wasbCyfv1U7KSKOc4ShgGbuPADKCykTpWoIiQeCt8tNMNOORs6Wa+dKDT'
    b'wlnupsOQ9aBkKaCYKmpYhtMUMgM/L7nFfULpxpAnbYhkHCVUUI4LDYjgp433dJA0w8MEJsko'
    b'lfNZz60Z+cfyH9QfKQn4S3u8bkoAAAAASUVORK5CYII=')

