from wx.lib.embeddedimage import PyEmbeddedImage
#----------------------------------------------------------------------
Actor = PyEmbeddedImage(
    b'iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAQAAABKfvVzAAAAOGVYSWZNTQAqAAAACAABh2kA'
    b'BAAAAAEAAAAaAAAAAAACoAIABAAAAAEAAAhWoAMABAAAAAEAAAhWAAAAAMFeALwAAAACYktH'
    b'RAD/h4/MvwAAAAd0SU1FB+oFDhcEAVk2KmAAAAAldEVYdGRhdGU6Y3JlYXRlADIwMjYtMDUt'
    b'MTRUMjI6NTc6MzIrMDA6MDAY2eYbAAAAJXRFWHRkYXRlOm1vZGlmeQAyMDI2LTA1LTE0VDIy'
    b'OjM5OjAzKzAwOjAwtwCoAAAAACh0RVh0ZGF0ZTp0aW1lc3RhbXAAMjAyNi0wNS0xNFQyMzow'
    b'NDowMSswMDowMMYArMIAAAASdEVYdGV4aWY6RXhpZk9mZnNldAAyNlMbomUAAAAZdEVYdGV4'
    b'aWY6UGl4ZWxYRGltZW5zaW9uADIxMzT4qaKHAAAAGXRFWHRleGlmOlBpeGVsWURpbWVuc2lv'
    b'bgAyMTM0QVJ5bwAAAD10RVh0aWNjOmNvcHlyaWdodABDb3B5cmlnaHQgMjAwNyBBcHBsZSBJ'
    b'bmMuLCBhbGwgcmlnaHRzIHJlc2VydmVkLp5m3CkAAAAjdEVYdGljYzpkZXNjcmlwdGlvbgBH'
    b'ZW5lcmljIFJHQiBQcm9maWxlGqc4jgAAASpJREFUOMu1kb1KA0EUhb+ZTbTICkm3Qp5BtLBy'
    b'C1sFbcRXEBF8h/gASiCpLdTGhSBoIFhaa6ld2MYiPxAIIRGiiWOz2ezujL+YO8UM95zvDmcG'
    b'Zl1icqiFrR3mGKCweaUSdjeCXUZgizxpOKULWZHtUgJIk8eamqLAIh4FMhWslVF1dGMt30KG'
    b'IzwcM9DCY59SMTd21Zpyx+5JjjJ7XNKemlIR4I0iDY4fz3bPq/eorfbTBUsc4BlDh7HXKYv5'
    b'3kCwYKsXDrmLRo4BIbLKtXBANdjmIW6PZ5gIPh2Fgg5+0p4AAlEG9wpk0q4B39dXgDI1U0ar'
    b'wP9smBmwuEKy+XMA3v+SYZaADJbQJVOGIXWekdQZ6qI2owbg0AdsmvpPm1+pCUD/t/n+pz4A'
    b'GUdHoDx3M+cAAAAASUVORK5CYII=')

#----------------------------------------------------------------------
Aggregation = PyEmbeddedImage(
    b'iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAQAAABKfvVzAAAAAmJLR0QA/4ePzL8AAAAJcEhZ'
    b'cwAALiMAAC4jAXilP3YAAAAHdElNRQfqBQ4XBAFZNipgAAAAJXRFWHRkYXRlOmNyZWF0ZQAy'
    b'MDI2LTA1LTE0VDIyOjU3OjMyKzAwOjAwGNnmGwAAACV0RVh0ZGF0ZTptb2RpZnkAMjAyNi0w'
    b'NS0xNFQyMjoxNTozOSswMDowMN+vqeIAAAAodEVYdGRhdGU6dGltZXN0YW1wADIwMjYtMDUt'
    b'MTRUMjM6MDQ6MDErMDA6MDDGAKzCAAAAuElEQVQ4y+2SOQ7CMBBFn7MaheU8SFyOiyAOwzVo'
    b'qJEgocjqDEV2BRJEnddY/vrf9swYFuZR1XLpSYfJgNWzewSoYfhjoDZoNlhs5yKqtQc8Mazw'
    b'VHST8GvAGdghhmKXJNIU16egqAI2ax6YSr3Hjp0f1b7Zt9icOTU3SKcLIggl5aif0tXgExDW'
    b'Z2rjX9NMGGOaJ0EK7AgxaDw30pJNDa7uk09AjuKFTA1P9Qbn4hJP2//4Ggu/8AbA+jtJXb8Q'
    b'RAAAAABJRU5ErkJggg==')

#----------------------------------------------------------------------
Association = PyEmbeddedImage(
    b'iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAQAAABKfvVzAAAAAmJLR0QA/4ePzL8AAAAJcEhZ'
    b'cwAALiMAAC4jAXilP3YAAAAHdElNRQfqBQ4XBAFZNipgAAAAJXRFWHRkYXRlOmNyZWF0ZQAy'
    b'MDI2LTA1LTE0VDIyOjU3OjMyKzAwOjAwGNnmGwAAACV0RVh0ZGF0ZTptb2RpZnkAMjAyNi0w'
    b'NS0xNFQyMjoxNTozOSswMDowMN+vqeIAAAAodEVYdGRhdGU6dGltZXN0YW1wADIwMjYtMDUt'
    b'MTRUMjM6MDQ6MDErMDA6MDDGAKzCAAAAS0lEQVQ4y2NgGAVDEjDOIFEDC5RkIULtH4Y/MA1J'
    b'DDEMfwkoZ2ZYzDAbpuE/wz+Gf4Qcz/Af4QcWBmYinPQX4aQ/DH+oFoyjYHACAMGdDjKJChcx'
    b'AAAAAElFTkSuQmCC')

#----------------------------------------------------------------------
Class = PyEmbeddedImage(
    b'iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAQAAABKfvVzAAAAAmJLR0QA/4ePzL8AAAAJcEhZ'
    b'cwAALiMAAC4jAXilP3YAAAAHdElNRQfqBQ4XBAFZNipgAAAAJXRFWHRkYXRlOmNyZWF0ZQAy'
    b'MDI2LTA1LTE0VDIyOjU3OjMyKzAwOjAwGNnmGwAAACV0RVh0ZGF0ZTptb2RpZnkAMjAyNi0w'
    b'NS0xNFQyMjoxNTozOSswMDowMN+vqeIAAAAodEVYdGRhdGU6dGltZXN0YW1wADIwMjYtMDUt'
    b'MTRUMjM6MDQ6MDErMDA6MDDGAKzCAAABSUlEQVQ4y72Sv0oDQRDGv9kzhtydGIMYJUIgTcBO'
    b'bK3zCD6F7+AziNpYWYgvYGNhYWFvq6ipAobE4sIll+TudsfCmD97I2ihX7PMMD92vm8X+GvR'
    b'53H/g9F9AMDSV8nk5LaNLwz20XJ0TIxFoEAd73WXPbC9Aw22nt2uGVnAHl+48QnXYSxA0WPv'
    b'oNidzM8AQKX0QjoLoOmks+bUtFKh03HhZD1wWl12IkSWaQPfBL1EML0GpzSr5lZiVCbRLWox'
    b'8jmA0MaVAAzgSQAhooFLKgu86dpcewrU+aYYH6GSfQe0guNylNhAk7wwOUVeSGnk9dPsDTE2'
    b'0/BJCx585EtMgmmN2u9SAjSuBYBBMkBoYCwA59iRgCrfrZ4doiyk1A4u14epDbRpI/f+wL7w'
    b'vfsFZThzw4hXwsptTlgpQU/pMdkAsRkG+E6E/9MHiJpvU2npp4wAAAAASUVORK5CYII=')

#----------------------------------------------------------------------
Composition = PyEmbeddedImage(
    b'iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAQAAABKfvVzAAAAOGVYSWZNTQAqAAAACAABh2kA'
    b'BAAAAAEAAAAaAAAAAAACoAIABAAAAAEAAAhWoAMABAAAAAEAAAhWAAAAAMFeALwAAAACYktH'
    b'RAD/h4/MvwAAAAd0SU1FB+oFDhcEAVk2KmAAAAAldEVYdGRhdGU6Y3JlYXRlADIwMjYtMDUt'
    b'MTRUMjI6NTc6MzIrMDA6MDAY2eYbAAAAJXRFWHRkYXRlOm1vZGlmeQAyMDI2LTA1LTE0VDIy'
    b'OjU3OjA2KzAwOjAwE0R9VwAAACh0RVh0ZGF0ZTp0aW1lc3RhbXAAMjAyNi0wNS0xNFQyMzow'
    b'NDowMSswMDowMMYArMIAAAASdEVYdGV4aWY6RXhpZk9mZnNldAAyNlMbomUAAAAZdEVYdGV4'
    b'aWY6UGl4ZWxYRGltZW5zaW9uADIxMzT4qaKHAAAAGXRFWHRleGlmOlBpeGVsWURpbWVuc2lv'
    b'bgAyMTM0QVJ5bwAAAD10RVh0aWNjOmNvcHlyaWdodABDb3B5cmlnaHQgMjAwNyBBcHBsZSBJ'
    b'bmMuLCBhbGwgcmlnaHRzIHJlc2VydmVkLp5m3CkAAAAjdEVYdGljYzpkZXNjcmlwdGlvbgBH'
    b'ZW5lcmljIFJHQiBQcm9maWxlGqc4jgAAANNJREFUOMvtkr0OAUEcxH/rrtCojkrlBTyC3gto'
    b'8AAKapVaI/ERrWgUJHLldRKJaBVeQK1RSmT3VuHuuHNZojZbbLIzk/nvzsIfnyEem/dyVDUa'
    b'Mi/yHCVE3JxqCAQOUzbUknlJ2JF8RB2YwG25NhkAyDOkDkCBiS0WbuptJRKEBzZjWk9GXfrH'
    b'nf9msJgzCxN0jNJo/JQEHY4k6ZGjGRBn0dm7CPt9KAVgNQCubClSBs605SqrDiqjSC4/KC56'
    b'pwEVuqzM5YlYcQ4ns/yHr/HHN7gD6886NfDN8n8AAAAASUVORK5CYII=')

#----------------------------------------------------------------------
Inheritance = PyEmbeddedImage(
    b'iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAQAAABKfvVzAAAAAmJLR0QA/4ePzL8AAAAJcEhZ'
    b'cwAALiMAAC4jAXilP3YAAAAHdElNRQfqBQ4XBAFZNipgAAAAJXRFWHRkYXRlOmNyZWF0ZQAy'
    b'MDI2LTA1LTE0VDIyOjU3OjMyKzAwOjAwGNnmGwAAACV0RVh0ZGF0ZTptb2RpZnkAMjAyNi0w'
    b'NS0xNFQyMjoxNTozOSswMDowMN+vqeIAAAAodEVYdGRhdGU6dGltZXN0YW1wADIwMjYtMDUt'
    b'MTRUMjM6MDQ6MDErMDA6MDDGAKzCAAABC0lEQVQ4y+2RPS+DURiGr+fxNtJKNDHxF2zMXaxC'
    b'OomByVSD2V8w+AE1GzFVzLba2gQJFtJEaulQklaavuc2vKJfefEDek/P+bjOc865YJq/Y2kL'
    b'5aG6NFT7L4flWVE2gQd4lN5aG17Uiyqh6v2kYwmwcirAvr9aI2wr6KJTyym5XAQ4C8qMA+rb'
    b'vBqq5+66Be3Orets8bFJmQhYsmP/IIwTLHMr4r6uZ296azp8O/crfb9BCE0APzMyDJJxBDR1'
    b'EDLj/6vY9twMz1iht6mWjrJPHYwICLQmdTi824ytdrcU67Rdy9PFKKWLO0E7XtSzKqHq8UBg'
    b'qgfBZbjXg336iO1UAGhTt5HN0/w3XzSmZvqus3ClAAAAAElFTkSuQmCC')

#----------------------------------------------------------------------
NewClassDiagram = PyEmbeddedImage(
    b'iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAQAAABKfvVzAAAAOGVYSWZNTQAqAAAACAABh2kA'
    b'BAAAAAEAAAAaAAAAAAACoAIABAAAAAEAAAhWoAMABAAAAAEAAAhWAAAAAMFeALwAAAACYktH'
    b'RAD/h4/MvwAAAAd0SU1FB+oFDhcEAVk2KmAAAAAldEVYdGRhdGU6Y3JlYXRlADIwMjYtMDUt'
    b'MTRUMjI6NTc6MzIrMDA6MDAY2eYbAAAAJXRFWHRkYXRlOm1vZGlmeQAyMDI2LTA1LTE0VDIy'
    b'OjQyOjI0KzAwOjAw4Vl/hwAAACh0RVh0ZGF0ZTp0aW1lc3RhbXAAMjAyNi0wNS0xNFQyMzow'
    b'NDowMSswMDowMMYArMIAAAASdEVYdGV4aWY6RXhpZk9mZnNldAAyNlMbomUAAAAZdEVYdGV4'
    b'aWY6UGl4ZWxYRGltZW5zaW9uADIxMzT4qaKHAAAAGXRFWHRleGlmOlBpeGVsWURpbWVuc2lv'
    b'bgAyMTM0QVJ5bwAAAD10RVh0aWNjOmNvcHlyaWdodABDb3B5cmlnaHQgMjAwNyBBcHBsZSBJ'
    b'bmMuLCBhbGwgcmlnaHRzIHJlc2VydmVkLp5m3CkAAAAjdEVYdGljYzpkZXNjcmlwdGlvbgBH'
    b'ZW5lcmljIFJHQiBQcm9maWxlGqc4jgAAAXBJREFUOMu90k9LAkEYx/HvzkZqpJlhCUWBRXkM'
    b'vHgIOkpEb6CgIioJegG9giA6dengO+gVdIg6eBE6dYroqIHU9t80s3Wng7auO+ux5jQ7zGee'
    b'5/mx8NdLa29PHccWt2wSx1BAj4uPEEIC9BmLrwZRhdhgDiDGCdNYgDi/zO2KgkpskKdAIlhN'
    b'EG2WMpboFdsoRLS7yfj3VipBx1DpRlaMC4zmG27QgFhp48vvLC89iA1kR2I6kRYxs9ZEiocu'
    b'KcnfzQspTN4A0kNH86sH796gpc7II4izjg+wkkSwgXBfFxS5YJkMH9yjo6FbOjpdK2iUiDCF'
    b'YAuwUB9UGgpRpoxJDsOZQ7cKkknGOCZAjVl1QC/gY40b6swQbsfWHYAkQBKwPK4rQGt1bbW+'
    b'QLrmdALtU3/E15GMIFDRilQ9gECWjetDEXLcl6L/amd/9K7h+F3t3AYJUxw2Bzoa13g+e6oj'
    b'gAU3CKBTU0bU+CZImf9cP/BLbLT+luf0AAAAAElFTkSuQmCC')

#----------------------------------------------------------------------
NewProject = PyEmbeddedImage(
    b'iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAQAAABKfvVzAAAAOGVYSWZNTQAqAAAACAABh2kA'
    b'BAAAAAEAAAAaAAAAAAACoAIABAAAAAEAAAhWoAMABAAAAAEAAAhWAAAAAMFeALwAAAACYktH'
    b'RAD/h4/MvwAAAAd0SU1FB+oFDhcEAVk2KmAAAAAldEVYdGRhdGU6Y3JlYXRlADIwMjYtMDUt'
    b'MTRUMjI6NTc6MzIrMDA6MDAY2eYbAAAAJXRFWHRkYXRlOm1vZGlmeQAyMDI2LTA1LTE0VDIy'
    b'OjUwOjAxKzAwOjAwND9YoAAAACh0RVh0ZGF0ZTp0aW1lc3RhbXAAMjAyNi0wNS0xNFQyMzow'
    b'NDowMSswMDowMMYArMIAAAASdEVYdGV4aWY6RXhpZk9mZnNldAAyNlMbomUAAAAZdEVYdGV4'
    b'aWY6UGl4ZWxYRGltZW5zaW9uADIxMzT4qaKHAAAAGXRFWHRleGlmOlBpeGVsWURpbWVuc2lv'
    b'bgAyMTM0QVJ5bwAAAD10RVh0aWNjOmNvcHlyaWdodABDb3B5cmlnaHQgMjAwNyBBcHBsZSBJ'
    b'bmMuLCBhbGwgcmlnaHRzIHJlc2VydmVkLp5m3CkAAAAjdEVYdGljYzpkZXNjcmlwdGlvbgBH'
    b'ZW5lcmljIFJHQiBQcm9maWxlGqc4jgAAAVtJREFUOMu1k7tOQkEQhr9dblEQEA6XQ6O1FhZa'
    b'SEJLQeILGCoL38aewqfQxtb4ACY2WlAYjGIgCIIYuZ2zFsC5IPHQMM3OJv838092B9YdYp7c'
    b'eEpLAPinly0eqHCZNBJLtV2a83QGfJGkqA8qgWNMYbcFTJBUKfPiAoKca/nCyYHMDOmiHECU'
    b'EETQFwAF/pCs1rOhZ72CackVZUoYhl1jBgQYN4aN7jCjery77HcWxpHTYwKZYDq/k8upBYFY'
    b'uPutbDxRt2+7G/v6GcZMphAcOQw6AAkd8yMVjG9qnLoEJmoZYEAunNpL+aIm/4e0nPb6o+va'
    b'46v0AOwZfvg+jGuaVwf7HfTYdjriD3joHZaan/2r2lN9dUsSUczGcisOrUCLhRGD0YqWJNQn'
    b'rbtWrb3Uks9+cMvSxaRw3+4gzPqSolX7gzk2TqASJFF/ADFdoJK7Ayho0/aaYf3xC3MzZhRr'
    b'Wj8kAAAAAElFTkSuQmCC')

#----------------------------------------------------------------------
NewSequenceDiagram = PyEmbeddedImage(
    b'iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAQAAABKfvVzAAAAOGVYSWZNTQAqAAAACAABh2kA'
    b'BAAAAAEAAAAaAAAAAAACoAIABAAAAAEAAAhWoAMABAAAAAEAAAhWAAAAAMFeALwAAAACYktH'
    b'RAD/h4/MvwAAAAd0SU1FB+oFDhcEAVk2KmAAAAAldEVYdGRhdGU6Y3JlYXRlADIwMjYtMDUt'
    b'MTRUMjI6NTc6MzIrMDA6MDAY2eYbAAAAJXRFWHRkYXRlOm1vZGlmeQAyMDI2LTA1LTE0VDIy'
    b'OjQ2OjM3KzAwOjAwFfDF/gAAACh0RVh0ZGF0ZTp0aW1lc3RhbXAAMjAyNi0wNS0xNFQyMzow'
    b'NDowMSswMDowMMYArMIAAAASdEVYdGV4aWY6RXhpZk9mZnNldAAyNlMbomUAAAAZdEVYdGV4'
    b'aWY6UGl4ZWxYRGltZW5zaW9uADIxMzT4qaKHAAAAGXRFWHRleGlmOlBpeGVsWURpbWVuc2lv'
    b'bgAyMTM0QVJ5bwAAAD10RVh0aWNjOmNvcHlyaWdodABDb3B5cmlnaHQgMjAwNyBBcHBsZSBJ'
    b'bmMuLCBhbGwgcmlnaHRzIHJlc2VydmVkLp5m3CkAAAAjdEVYdGljYzpkZXNjcmlwdGlvbgBH'
    b'ZW5lcmljIFJHQiBQcm9maWxlGqc4jgAAAW1JREFUOMu90r8vg0EYwPHv3SuUaClpNUElBhGT'
    b'RBoGCVsjIrFLDCIViZj9BRIxWf0BFavFIBaLxMLCYJEUEd5qmlZ/0PY9w/uqt+/7qolnutzd'
    b'5+55njv46xDfw2PbtMEtqwyju0CLg/cRQAF06PNZnZCL1ME0QIRDRjAAeXpxtiFTblIH56QY'
    b'9RdHCZlX6Qu0ygQuIr+zWfNtLRX8tqLitX0ZlejmGU5Qg8jTyrvPfr3yIHWgGjqmEbRIdd8Y'
    b'muLlhy4pM7kKWWZRZBAQ792bWd7JeQNAkOeANIpFxjAAY4IemoFHrtkkR9V6V82wr0snUAww'
    b'TpJLwniFdE+VmCRBmSNP4JHSG0mGeSaGMLvQHBgMscYdMeuP/AoABomiPLe7gEAACsXXOypH'
    b'nXYgSlqatoaTJe0FcU/RA0hUXr/ZlQHbfiU7r9a3+x9quj0HK4J0cx+udjU0RpA5ef1AAnNO'
    b'0I5G2VWioIKfPP8Zn4NlbZEMjLooAAAAAElFTkSuQmCC')

#----------------------------------------------------------------------
NewUseCaseDiagram = PyEmbeddedImage(
    b'iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAQAAABKfvVzAAAAOGVYSWZNTQAqAAAACAABh2kA'
    b'BAAAAAEAAAAaAAAAAAACoAIABAAAAAEAAAhWoAMABAAAAAEAAAhWAAAAAMFeALwAAAACYktH'
    b'RAD/h4/MvwAAAAd0SU1FB+oFDhcEAVk2KmAAAAAldEVYdGRhdGU6Y3JlYXRlADIwMjYtMDUt'
    b'MTRUMjI6NTc6MzIrMDA6MDAY2eYbAAAAJXRFWHRkYXRlOm1vZGlmeQAyMDI2LTA1LTE0VDIy'
    b'OjQ2OjM3KzAwOjAwFfDF/gAAACh0RVh0ZGF0ZTp0aW1lc3RhbXAAMjAyNi0wNS0xNFQyMzow'
    b'NDowMSswMDowMMYArMIAAAASdEVYdGV4aWY6RXhpZk9mZnNldAAyNlMbomUAAAAZdEVYdGV4'
    b'aWY6UGl4ZWxYRGltZW5zaW9uADIxMzT4qaKHAAAAGXRFWHRleGlmOlBpeGVsWURpbWVuc2lv'
    b'bgAyMTM0QVJ5bwAAAD10RVh0aWNjOmNvcHlyaWdodABDb3B5cmlnaHQgMjAwNyBBcHBsZSBJ'
    b'bmMuLCBhbGwgcmlnaHRzIHJlc2VydmVkLp5m3CkAAAAjdEVYdGljYzpkZXNjcmlwdGlvbgBH'
    b'ZW5lcmljIFJHQiBQcm9maWxlGqc4jgAAAWdJREFUOMu90rtLAzEcwPFvcj5a6cNTq7WCgoPU'
    b'2UVBcCxS3AXBQUpF8A/wLxDEydH+B/4FHcTFRXByEnFsBaGnIpbWPq6JQ8v12rsWF82UhHzy'
    b'eyTw10N0p3nXtuKZDMtYHjDSx+eIoAEmrPSnRcxDHLAJEOeKFRQgb+5vj2XBSxxwR4FkuJok'
    b'1g5l7TAms3iI7GZzGDjZq4RdRaVaObkosdp39IMWxF8P6gF3eO1DHKBdHRNIzA6xc2ppndKA'
    b'Lul2rBoh0pSpYUBq+mJr/+zLHwCSAnkymIyySwKNWmOKwQAaWGhalLCRKAzVe6Hv84veTzAc'
    b'GNRp0qCJ4QM8KWnmMbnEJsEM6jcgRJYnJKsE2m0bDkATZQNQPsc9QHRKVZ0V6L463UB8G2+M'
    b'9+QtCVZEkaoPkOiy9XguI67zWoYejk4XXlqu7+o022SS4qwd7Ulc8HH93kAC2/0giEHNU6Kg'
    b'SZgy/zl+AIL/bKAcQ5+cAAAAAElFTkSuQmCC')

#----------------------------------------------------------------------
Note = PyEmbeddedImage(
    b'iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAQAAABKfvVzAAAAOGVYSWZNTQAqAAAACAABh2kA'
    b'BAAAAAEAAAAaAAAAAAACoAIABAAAAAEAAAhWoAMABAAAAAEAAAhWAAAAAMFeALwAAAACYktH'
    b'RAD/h4/MvwAAAAd0SU1FB+oFDhcEAVk2KmAAAAAldEVYdGRhdGU6Y3JlYXRlADIwMjYtMDUt'
    b'MTRUMjI6NTc6MzIrMDA6MDAY2eYbAAAAJXRFWHRkYXRlOm1vZGlmeQAyMDI2LTA1LTE0VDIy'
    b'OjUwOjAxKzAwOjAwND9YoAAAACh0RVh0ZGF0ZTp0aW1lc3RhbXAAMjAyNi0wNS0xNFQyMzow'
    b'NDowMSswMDowMMYArMIAAAASdEVYdGV4aWY6RXhpZk9mZnNldAAyNlMbomUAAAAZdEVYdGV4'
    b'aWY6UGl4ZWxYRGltZW5zaW9uADIxMzT4qaKHAAAAGXRFWHRleGlmOlBpeGVsWURpbWVuc2lv'
    b'bgAyMTM0QVJ5bwAAAD10RVh0aWNjOmNvcHlyaWdodABDb3B5cmlnaHQgMjAwNyBBcHBsZSBJ'
    b'bmMuLCBhbGwgcmlnaHRzIHJlc2VydmVkLp5m3CkAAAAjdEVYdGljYzpkZXNjcmlwdGlvbgBH'
    b'ZW5lcmljIFJHQiBQcm9maWxlGqc4jgAAAT1JREFUOMu9k7FOwzAQhj+7CYlSSiFCQqpaCiuI'
    b'iXeo1Ddg5gnYeBgWxMTOAAPiLTozIEBCRQiGSm1ojsGUnJsoTHAZYl/u8+//7MBfh3Gv61/K'
    b'hj+jQI16RBULvvKiEwVwwCXrVvRHQQJuOGZWBbTZzuJHPhWQksIOYTUAIsyZ6/UxSI4UHoce'
    b'gCHyEgHiyJQ9RrwtKyBMvC0lGAQCjgjZ54wcrAYsLdbUEzmFGOEc63roKcx5J1PzFdqLTVny'
    b'smkabCzygJDgdZkKhTHZ4vARGrRKSOBPtlRbYbVewZDx7HnoVCAKEEI6ygM0dblUKjwoBaFL'
    b'E5FahT65Mp0g7gdwt2QJmJo8417fM3p0kV363NIhZ+oDI7mIB4emKDeIUzjljpArZ68APjhh'
    b'U6ze4ndYYMykfA4znqiNIf8RXxdzYck0UDwdAAAAAElFTkSuQmCC')

#----------------------------------------------------------------------
NoteAssociation = PyEmbeddedImage(
    b'iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAQAAABKfvVzAAAAOGVYSWZNTQAqAAAACAABh2kA'
    b'BAAAAAEAAAAaAAAAAAACoAIABAAAAAEAAAhWoAMABAAAAAEAAAhWAAAAAMFeALwAAAACYktH'
    b'RAD/h4/MvwAAAAd0SU1FB+oFDhcEAVk2KmAAAAAldEVYdGRhdGU6Y3JlYXRlADIwMjYtMDUt'
    b'MTRUMjM6MDM6MDUrMDA6MDD22wrLAAAAJXRFWHRkYXRlOm1vZGlmeQAyMDI2LTA1LTE0VDIz'
    b'OjAxOjM1KzAwOjAwDfxlqQAAACh0RVh0ZGF0ZTp0aW1lc3RhbXAAMjAyNi0wNS0xNFQyMzow'
    b'NDowMSswMDowMMYArMIAAAASdEVYdGV4aWY6RXhpZk9mZnNldAAyNlMbomUAAAAZdEVYdGV4'
    b'aWY6UGl4ZWxYRGltZW5zaW9uADIxMzT4qaKHAAAAGXRFWHRleGlmOlBpeGVsWURpbWVuc2lv'
    b'bgAyMTM0QVJ5bwAAAD10RVh0aWNjOmNvcHlyaWdodABDb3B5cmlnaHQgMjAwNyBBcHBsZSBJ'
    b'bmMuLCBhbGwgcmlnaHRzIHJlc2VydmVkLp5m3CkAAAAjdEVYdGljYzpkZXNjcmlwdGlvbgBH'
    b'ZW5lcmljIFJHQiBQcm9maWxlGqc4jgAAAINJREFUOMvt0DEKwlAAg+HPIi0VPII3cBFcHAQR'
    b'RHBwEEQEL+XsBVwchIIgjq4dexzfcxGLF9DB/kMIIVlCw3/Qqu3VQ26CngP2LjhLJebvVgL6'
    b'drqGNnJjK5mZhdTSVGZtpGNrUA+i8KFRFBEEBJFXog0qFUol7uAGCnACx1+/1/BdnlwRHs9k'
    b'kFllAAAAAElFTkSuQmCC')

#----------------------------------------------------------------------
OpenProject = PyEmbeddedImage(
    b'iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAQAAABKfvVzAAAAOGVYSWZNTQAqAAAACAABh2kA'
    b'BAAAAAEAAAAaAAAAAAACoAIABAAAAAEAAAhWoAMABAAAAAEAAAhWAAAAAMFeALwAAAACYktH'
    b'RAD/h4/MvwAAAAd0SU1FB+oFDhcEAVk2KmAAAAAldEVYdGRhdGU6Y3JlYXRlADIwMjYtMDUt'
    b'MTRUMjI6NTc6MzMrMDA6MDC+ru2vAAAAJXRFWHRkYXRlOm1vZGlmeQAyMDI2LTA1LTE0VDIy'
    b'OjUwOjAxKzAwOjAwND9YoAAAACh0RVh0ZGF0ZTp0aW1lc3RhbXAAMjAyNi0wNS0xNFQyMzow'
    b'NDowMSswMDowMMYArMIAAAASdEVYdGV4aWY6RXhpZk9mZnNldAAyNlMbomUAAAAZdEVYdGV4'
    b'aWY6UGl4ZWxYRGltZW5zaW9uADIxMzT4qaKHAAAAGXRFWHRleGlmOlBpeGVsWURpbWVuc2lv'
    b'bgAyMTM0QVJ5bwAAAD10RVh0aWNjOmNvcHlyaWdodABDb3B5cmlnaHQgMjAwNyBBcHBsZSBJ'
    b'bmMuLCBhbGwgcmlnaHRzIHJlc2VydmVkLp5m3CkAAAAjdEVYdGljYzpkZXNjcmlwdGlvbgBH'
    b'ZW5lcmljIFJHQiBQcm9maWxlGqc4jgAAAWxJREFUOMvNkz1LA0EQhp+5M194oILJCWoqbays'
    b'tLATGxtJpX9D/AcWIlgJ/gLblKJYaSW2Vun8AK3yAWJiNGdyOxY57y4hMZXgVLPsPPO+O7sL'
    b'fx0CcDlgY3MIMBZmGaaxAKVCa7TCGIdso4Bwyj7+oOLNmMI46+SDfI97LrBiTQ1vtPstGcHy'
    b'AEjIEbvxzn5Sixx0VUNApHJzXtMUCmJ1raplFMTbyuYKeky9B7D0vllcZQKNrIyXFqpY+K93'
    b'blK1z5LaToNbnBAQ5+l4Nr+mCmqbM756AaVkvy/OxRp0dtz5DT8TLJdI4cUBz3hLhZPIDiiT'
    b'JhNb9V1cmmVm4vXDIhqrSnc0gKKjAaFJORiFQ05GAvDJMwooLu5QjfABKDU80zZt0zFVU1b5'
    b'HRB8HtWShCQkIQ15YBgQ3bRMSZ0OADaTMrhxCGhTrlemff3RszHxcuGKj5+U4MelJRv56Duy'
    b'UqXV+x+gpS/8i/gGcGV6yOOfiioAAAAASUVORK5CYII=')

#----------------------------------------------------------------------
Pointer = PyEmbeddedImage(
    b'iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAQAAABKfvVzAAAAOGVYSWZNTQAqAAAACAABh2kA'
    b'BAAAAAEAAAAaAAAAAAACoAIABAAAAAEAAAhWoAMABAAAAAEAAAhWAAAAAMFeALwAAAACYktH'
    b'RAD/h4/MvwAAAAd0SU1FB+oFDhcEAVk2KmAAAAAldEVYdGRhdGU6Y3JlYXRlADIwMjYtMDUt'
    b'MTRUMjI6NTc6MzMrMDA6MDC+ru2vAAAAJXRFWHRkYXRlOm1vZGlmeQAyMDI2LTA1LTE0VDIy'
    b'OjUwOjAxKzAwOjAwND9YoAAAACh0RVh0ZGF0ZTp0aW1lc3RhbXAAMjAyNi0wNS0xNFQyMzow'
    b'NDowMSswMDowMMYArMIAAAASdEVYdGV4aWY6RXhpZk9mZnNldAAyNlMbomUAAAAZdEVYdGV4'
    b'aWY6UGl4ZWxYRGltZW5zaW9uADIxMzT4qaKHAAAAGXRFWHRleGlmOlBpeGVsWURpbWVuc2lv'
    b'bgAyMTM0QVJ5bwAAAD10RVh0aWNjOmNvcHlyaWdodABDb3B5cmlnaHQgMjAwNyBBcHBsZSBJ'
    b'bmMuLCBhbGwgcmlnaHRzIHJlc2VydmVkLp5m3CkAAAAjdEVYdGljYzpkZXNjcmlwdGlvbgBH'
    b'ZW5lcmljIFJHQiBQcm9maWxlGqc4jgAAAjZJREFUOMu1k8tLVHEUgL/fvVe9c8eZwXHy0fhI'
    b'klSENI0ei3JTECXMIFi4qahFq4rWQiv/gDZiC9tWEIQSIuOmUkrwVWmoIWpaTsj0UhjMO849'
    b'LUycEcoWdXYHzne+c+Ac+N+hQNHzK1nD5NzugEULnVqfNxmfT/jxAYLCJvw7wE1cXbvReMlY'
    b'XBnTXwen65bMeDslGAgGNo07AZMfrrLe1oYAHcQSRbGi2eD43rH8CfXe+UpyFY0LKYAOLuyN'
    b'1f2FJ6sxSOgfPW9Kh44Mh4zm8jANul+mMxIP0w0e4jh1dZHWgAfBZoUoc5RRg2J8/UHIFXmR'
    b'AmhwiCx4O9M/BTgYBKiliVpglnufxqKDaTvosICDJG3NFT6sKQAEQXB4/H3ges6ztTTAAAiy'
    b'jP10fDJ6sBgnRX7evrg+TyUOZ1NHgg/kwvJS9wgqrZsvL7Oz4mpSh166t0fa5DZwVp2mo1Ym'
    b'oFBbqJtTSmNYJXRauL9lgNOYMDHTP42Oxku6sLcQi9vqjuwBg55twxRJJGlrEq7QJrn7eUCL'
    b'G5WYyKa+XlVZQ3PfWrYB2EccFVs8M5j/fCl2hdF3x6NmJZ5NBDkwGrj5pMRZSV2xANCbeEQI'
    b'BK2ZhWppl4j0SkTapLSLTHf6HXrwAkENfFiAcYJXxdImPXJHyuc4Brd2nq4fPz785OLBD2RU'
    b'0eeTegl+IQQF5P3pUXIAjaxCOhjhMrjx7vJaFAIGXsP0gYW1WzlADVlYmGST/Tfl/yh+Ap3y'
    b'uV+CFRjeAAAAAElFTkSuQmCC')

#----------------------------------------------------------------------
Realization = PyEmbeddedImage(
    b'iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAQAAABKfvVzAAAAOGVYSWZNTQAqAAAACAABh2kA'
    b'BAAAAAEAAAAaAAAAAAACoAIABAAAAAEAAAhWoAMABAAAAAEAAAhWAAAAAMFeALwAAAACYktH'
    b'RAD/h4/MvwAAAAd0SU1FB+oFDhcEAsA/e9oAAAAldEVYdGRhdGU6Y3JlYXRlADIwMjYtMDUt'
    b'MTRUMjM6MDM6MTErMDA6MDDOPi5GAAAAJXRFWHRkYXRlOm1vZGlmeQAyMDI2LTA1LTE0VDIz'
    b'OjAxOjM1KzAwOjAwDfxlqQAAACh0RVh0ZGF0ZTp0aW1lc3RhbXAAMjAyNi0wNS0xNFQyMzow'
    b'NDowMSswMDowMMYArMIAAAASdEVYdGV4aWY6RXhpZk9mZnNldAAyNlMbomUAAAAZdEVYdGV4'
    b'aWY6UGl4ZWxYRGltZW5zaW9uADIxMzT4qaKHAAAAGXRFWHRleGlmOlBpeGVsWURpbWVuc2lv'
    b'bgAyMTM0QVJ5bwAAAD10RVh0aWNjOmNvcHlyaWdodABDb3B5cmlnaHQgMjAwNyBBcHBsZSBJ'
    b'bmMuLCBhbGwgcmlnaHRzIHJlc2VydmVkLp5m3CkAAAAjdEVYdGljYzpkZXNjcmlwdGlvbgBH'
    b'ZW5lcmljIFJHQiBQcm9maWxlGqc4jgAAAQpJREFUOMvtkjlLA2EURc+3TOK4TAZcSECCG+nG'
    b'qIVLXAqLQBCbdPZ2tlpYCyLYCmIpNlapLNP7CwSxEBfQYgQbJSoyz0IFi+gM2Ob058G990GL'
    b'f6ExaBws/ckEhfEZJaVJ4TAWL3TRuVp6GD5iGq1wSbPyt5Als7Et+1INc3sEIeDjYiwGkKYZ'
    b'VGmhHBC0Fybt8mZP48o+NjAW3Us+eqPCEx6L3FFggltmX/vaBubKOSDLuDcy/7x0fW4vtUKJ'
    b'TlCBgAiAxaG54JFZ35G6nMiuVG66txjsAOz7rzddXlTEBfXw9Pj+oHZWJU0UV+tMOHTIFOqz'
    b'1rXYpX2C7+GK8TEN9us18glKafGTDy/bOlz2pQ29AAAAAElFTkSuQmCC')

#----------------------------------------------------------------------
Redo = PyEmbeddedImage(
    b'iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAQAAABKfvVzAAAAAmJLR0QA/4ePzL8AAAAJcEhZ'
    b'cwAALiMAAC4jAXilP3YAAAAHdElNRQfqBQ4XBALAP3vaAAAAJXRFWHRkYXRlOmNyZWF0ZQAy'
    b'MDI2LTA1LTE0VDIyOjU3OjMzKzAwOjAwvq7trwAAACV0RVh0ZGF0ZTptb2RpZnkAMjAyNi0w'
    b'NS0xNFQyMjoxNTo0MCswMDowMEDy5SgAAAAodEVYdGRhdGU6dGltZXN0YW1wADIwMjYtMDUt'
    b'MTRUMjM6MDQ6MDIrMDA6MDD36LZfAAABu0lEQVQ4y7WTPWgUQRTHf292N7d73uWEnOEam0Cw'
    b'sdBGLA5EsYpFELGOTYylvU0aG4tEBEvBxiIQSGenGDhQBEFiQkBU/MQIxmi4y2b35vZZ7Old'
    b'ltVck1fNzPt/vDdvBg46JO+w0beuZ3Lmn1Jummvsoec4/E2PkhARYtPtOeIs4SZner4uFbbw'
    b'8FF2idAEwyaTuBllwaeAMR2/+dQW7W54TdaK8XBsf0VD1vYcunCfohefaqH3S50qNR1lRCuU'
    b'5bDz01+wrwMupw5deMkxp7fu1VYm9Kye4KgO4+MBLRY7D+K3yhD0SuJQgVXz6rpO6zEivrLJ'
    b'ETwsj5iTx2oFoZkSSgCe660G8R29xAo3WOY9FR7SYl4WdRsEw/SfW2oAUt42n24lV7jNPBsg'
    b'UNaLPOGjoBiu9s+hAQSVlyfbS9w1s4ltUuYbF3iO8IZxZnImbYx2zrMuc4kVqsxQ4wUOhuMZ'
    b'eLdpQ9NjjAX9oQRMQV8J2TAARW17YnkGDlP7vFYD8F2x8pmN/ynvKclHQveDDfdFpw51YCws'
    b'vPMSdwBCF7OcBOtOrIMTqsiXKP/75TVdZ4cdbWs8SBMHHr8BeiWT2Vkh/iAAAAAASUVORK5C'
    b'YII=')

#----------------------------------------------------------------------
SaveProject = PyEmbeddedImage(
    b'iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAQAAABKfvVzAAAAOGVYSWZNTQAqAAAACAABh2kA'
    b'BAAAAAEAAAAaAAAAAAACoAIABAAAAAEAAAhWoAMABAAAAAEAAAhWAAAAAMFeALwAAAACYktH'
    b'RAD/h4/MvwAAAAd0SU1FB+oFDhcEAsA/e9oAAAAldEVYdGRhdGU6Y3JlYXRlADIwMjYtMDUt'
    b'MTRUMjI6NTc6MzMrMDA6MDC+ru2vAAAAJXRFWHRkYXRlOm1vZGlmeQAyMDI2LTA1LTE0VDIy'
    b'OjQ0OjM4KzAwOjAw501lKgAAACh0RVh0ZGF0ZTp0aW1lc3RhbXAAMjAyNi0wNS0xNFQyMzow'
    b'NDowMiswMDowMPfotl8AAAASdEVYdGV4aWY6RXhpZk9mZnNldAAyNlMbomUAAAAZdEVYdGV4'
    b'aWY6UGl4ZWxYRGltZW5zaW9uADIxMzT4qaKHAAAAGXRFWHRleGlmOlBpeGVsWURpbWVuc2lv'
    b'bgAyMTM0QVJ5bwAAAD10RVh0aWNjOmNvcHlyaWdodABDb3B5cmlnaHQgMjAwNyBBcHBsZSBJ'
    b'bmMuLCBhbGwgcmlnaHRzIHJlc2VydmVkLp5m3CkAAAAjdEVYdGljYzpkZXNjcmlwdGlvbgBH'
    b'ZW5lcmljIFJHQiBQcm9maWxlGqc4jgAAAW9JREFUOMvF07FuE0EUBdAzu+tgCCECBSkFBZFp'
    b'KGhooKSDSJao6GloaeAT+Ap+w0UKipRQRAgkKkqQkGMMSowUULy7Q5G1s7s2EQ3iTTNv5t6Z'
    b'++bO419HgJ15uua8dek8z41Mqvk2yOZ7my4ZHR1c7oZrIURctOprkX5x1aEJO7ZrhNQLD73J'
    b'X//oXb/fSUi8suvJcb4b74QPnhpq3BBs2NDXz3V0wJ6XHikf46bPnp0Ak7mk2C4vKk8Xt2aF'
    b'JYuwQqnAlntWZ5Q5M2vCg5/enzydnucO/aqyPxCi3LfWEWcQzllvbRMdOF5OiK64teBs9Na4'
    b'dkzjhuDInmkNfMHts2sgqamOCwKXEEKjzL8gxPqjL7o5I+Q6lYeloiapRJCKphW0crrvo4Hv'
    b'KBTyahQKwb6BT/ptSVlYQdfdhrxEhhVpaEkaxN74xijm75YY1/UgK8eD6g+fdtymtSJOtSPo'
    b'SIKJfY0GYmiY1prz/8VvyzZqbXK4U9QAAAAASUVORK5CYII=')

#----------------------------------------------------------------------
SequenceDiagramInstance = PyEmbeddedImage(
    b'iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAQAAABKfvVzAAAAOGVYSWZNTQAqAAAACAABh2kA'
    b'BAAAAAEAAAAaAAAAAAACoAIABAAAAAEAAAhWoAMABAAAAAEAAAhWAAAAAMFeALwAAAACYktH'
    b'RAD/h4/MvwAAAAd0SU1FB+oFDhcEAsA/e9oAAAAldEVYdGRhdGU6Y3JlYXRlADIwMjYtMDUt'
    b'MTRUMjM6MDM6MTgrMDA6MDBbpmuVAAAAJXRFWHRkYXRlOm1vZGlmeQAyMDI2LTA1LTE0VDIz'
    b'OjAxOjM1KzAwOjAwDfxlqQAAACh0RVh0ZGF0ZTp0aW1lc3RhbXAAMjAyNi0wNS0xNFQyMzow'
    b'NDowMiswMDowMPfotl8AAAASdEVYdGV4aWY6RXhpZk9mZnNldAAyNlMbomUAAAAZdEVYdGV4'
    b'aWY6UGl4ZWxYRGltZW5zaW9uADIxMzT4qaKHAAAAGXRFWHRleGlmOlBpeGVsWURpbWVuc2lv'
    b'bgAyMTM0QVJ5bwAAAD10RVh0aWNjOmNvcHlyaWdodABDb3B5cmlnaHQgMjAwNyBBcHBsZSBJ'
    b'bmMuLCBhbGwgcmlnaHRzIHJlc2VydmVkLp5m3CkAAAAjdEVYdGljYzpkZXNjcmlwdGlvbgBH'
    b'ZW5lcmljIFJHQiBQcm9maWxlGqc4jgAAARtJREFUOMvNkL1KA0EUhb87WdjEsLpVtEsXyROE'
    b'lD6AjVpZCJapU/kEFnkPKy3FgIjgQ0TzAgFTiLLEn/0bi0yWTXYXs6Dgbe4d7vnmnBn465J5'
    b'O19DegaAlZy3okZUIK1QmfLGCrDvDGpa54b4kPc+FyuArrs7DQSIAZXqmimzusmOSi7SIIwZ'
    b'IQiPPCEII8bzZybWVtpac8snuwhDFC0012zQWgpoLac9JkYhnAAKzSlq8ZEZQCICNoEAcAHf'
    b'9IA4FT0BZPLy4C3m+HUb3GdtZAEyyTrceHdfZjwM947g/vLKbG1sPwuEdmibsYc3hJ5/kMh+'
    b'rjbt/IUqAJo0178doEq1nEOHTv7CKgBm5QKBg1MuUpfuLzn8w/oGVI9ChZ2WGroAAAAASUVO'
    b'RK5CYII=')

#----------------------------------------------------------------------
SequenceDiagramMessage = PyEmbeddedImage(
    b'iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAQAAABKfvVzAAAAOGVYSWZNTQAqAAAACAABh2kA'
    b'BAAAAAEAAAAaAAAAAAACoAIABAAAAAEAAAhWoAMABAAAAAEAAAhWAAAAAMFeALwAAAACYktH'
    b'RAD/h4/MvwAAAAd0SU1FB+oFDhcEAsA/e9oAAAAldEVYdGRhdGU6Y3JlYXRlADIwMjYtMDUt'
    b'MTRUMjM6MDM6MjErMDA6MDBAsSmlAAAAJXRFWHRkYXRlOm1vZGlmeQAyMDI2LTA1LTE0VDIz'
    b'OjAxOjM1KzAwOjAwDfxlqQAAACh0RVh0ZGF0ZTp0aW1lc3RhbXAAMjAyNi0wNS0xNFQyMzow'
    b'NDowMiswMDowMPfotl8AAAASdEVYdGV4aWY6RXhpZk9mZnNldAAyNlMbomUAAAAZdEVYdGV4'
    b'aWY6UGl4ZWxYRGltZW5zaW9uADIxMzT4qaKHAAAAGXRFWHRleGlmOlBpeGVsWURpbWVuc2lv'
    b'bgAyMTM0QVJ5bwAAAD10RVh0aWNjOmNvcHlyaWdodABDb3B5cmlnaHQgMjAwNyBBcHBsZSBJ'
    b'bmMuLCBhbGwgcmlnaHRzIHJlc2VydmVkLp5m3CkAAAAjdEVYdGljYzpkZXNjcmlwdGlvbgBH'
    b'ZW5lcmljIFJHQiBQcm9maWxlGqc4jgAAAY9JREFUOMvtks9LVFEYhp/vnHPP3Ln+IDVGDWkR'
    b'iUSLQWkhKRjlopJZBK7Ude1ctG/VnyEkEe4E/wJbVIuiKF2Eugi5DKgZjWLMpOPc87WIIsV+'
    b'QKugZ/nxvZv3eeE/f0gv01iEGAFaGCAGYjwx+ZMCeXJYhAgh+n59Ab4EQNMPvwLdHFDBjocz'
    b'0cPDSWJpSBrOs2reFe5/frn76PTmR5RW9r5lDBbXb2dlyV2TZZk3z8wTc8cljEzt39PBN/Ft'
    b'2hMM0A5Y8JjmcCus0yd5LbArFW2VV36l0TE4NeaLXd03D4Y3aiGN6lWasAD0aaeU+SQZG1KR'
    b't7JFIbTpxf7RCy5HrymeLZT2L+2Ue9IaDjIohmkgU1BQg6Jaojl4IaB0cj3XuFFO06eJOnDY'
    b'BV3UY81JVr9s50gMdZZZXH89u/fAqMWBIFWtyrFABh+MBlZ5vPV8bntmfG0exf1cpoGhsdrE'
    b'Ts8MA19dxL+2b3EdyV2uYIUcnqu/m4vBcApPhOPcUdMnM8R7DjF41v5+rP86XwCyz3mvTxG2'
    b'xAAAAABJRU5ErkJggg==')

#----------------------------------------------------------------------
Text = PyEmbeddedImage(
    b'iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAQAAABKfvVzAAAAOGVYSWZNTQAqAAAACAABh2kA'
    b'BAAAAAEAAAAaAAAAAAACoAIABAAAAAEAAAhWoAMABAAAAAEAAAhWAAAAAMFeALwAAAACYktH'
    b'RAD/h4/MvwAAAAd0SU1FB+oFDhcEAsA/e9oAAAAldEVYdGRhdGU6Y3JlYXRlADIwMjYtMDUt'
    b'MTRUMjI6NTc6MzMrMDA6MDC+ru2vAAAAJXRFWHRkYXRlOm1vZGlmeQAyMDI2LTA1LTE0VDIy'
    b'OjQ3OjQ3KzAwOjAw8Pen2QAAACh0RVh0ZGF0ZTp0aW1lc3RhbXAAMjAyNi0wNS0xNFQyMzow'
    b'NDowMiswMDowMPfotl8AAAASdEVYdGV4aWY6RXhpZk9mZnNldAAyNlMbomUAAAAZdEVYdGV4'
    b'aWY6UGl4ZWxYRGltZW5zaW9uADIxMzT4qaKHAAAAGXRFWHRleGlmOlBpeGVsWURpbWVuc2lv'
    b'bgAyMTM0QVJ5bwAAAD10RVh0aWNjOmNvcHlyaWdodABDb3B5cmlnaHQgMjAwNyBBcHBsZSBJ'
    b'bmMuLCBhbGwgcmlnaHRzIHJlc2VydmVkLp5m3CkAAAAjdEVYdGljYzpkZXNjcmlwdGlvbgBH'
    b'ZW5lcmljIFJHQiBQcm9maWxlGqc4jgAAAXBJREFUOMu9k88uQ0EUxn/ndu5tm7ZUwkWrWgke'
    b'QLCwZWdrzcojeAM7L2DhFdgLD2BjLRIR6Z9UNEGQVNvbjsX905HcSmx6ZnPmm++b78zMGRhL'
    b'uFjYWCPX/dU5ACSEVKpbxB6h6DkN71ujfcEul4jrnTg7SqFj6OJ5nSt1pFsFaigAD/ZK+4fk'
    b'Df4gKlF45eygfsOpABY4AKUlVgy6wyq5YJ5kgwqUoAmo8BhCl88g16To0+YLQdOnH+A938Eo'
    b'NiYj2CIMhZFmjJKEFBkESP6SG4I2rShPU+SDFoImS8GQqKHpBOUItkkwEzg6WHElCW/cR4fO'
    b'MEWDZyw0OfLxDtOkDNimHDSDQsU7vHAXibNs8kgTQTPJeryDSzaCEzgss4D8x+FhlIMOSBUq'
    b'xn1brBn76oDsofwHp/7ELZPxzco7VajDfNitCeS8tnW8rRLEhtfvXKsLzWDYNIJK9xb/+EDV'
    b'XttwdxFsLGTE8L/oLOOJHw9RZRISiaCGAAAAAElFTkSuQmCC')

#----------------------------------------------------------------------
Undo = PyEmbeddedImage(
    b'iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAQAAABKfvVzAAAAAmJLR0QA/4ePzL8AAAAJcEhZ'
    b'cwAALiMAAC4jAXilP3YAAAAHdElNRQfqBQ4XBALAP3vaAAAAJXRFWHRkYXRlOmNyZWF0ZQAy'
    b'MDI2LTA1LTE0VDIyOjU3OjMzKzAwOjAwvq7trwAAACV0RVh0ZGF0ZTptb2RpZnkAMjAyNi0w'
    b'NS0xNFQyMjoxNTo0MCswMDowMEDy5SgAAAAodEVYdGRhdGU6dGltZXN0YW1wADIwMjYtMDUt'
    b'MTRUMjM6MDQ6MDIrMDA6MDD36LZfAAABsUlEQVQ4y7WSPWsUURSGn3Nn7m4mcRPBQrAQIlj4'
    b'UYjYueiCpLIRC7VNBLeSoFa21vZiAkrKqI3/IEhEsdEuoIWkEGFJxMx+zM7XPRZLknEY2C30'
    b'rQ6X97nv4ZwD/1tSftgs1M0KwK80GwzZmITNwy8C6hg61SkCbzmGIiDUCBBiUubYI8eNTK1C'
    b'nA8Zjtg7Wvd9m58Ln7mAkMuDZMYZHENidKOQJPCaPvZ0fCuf1d90ZY9d6dDxdhYHaj5NpzUG'
    b'DA+bE1jnF8bTiyxzkwBIiCRkWz7Lhnm/1Pk4m+f09hGBlySAIlYXeEgLj4RvHOE4VrZkxa6d'
    b'd7HSPwAAVskRFJnTOywzxXVCTnGV25w1r+yDM1HWJ7uCKy5uZX8o87TkDV1FkRM84r5ZPfm4'
    b'odqFZnnTz7EkKAGWHnWGiNUn0vZvXPgShdDE/A20EQweKQPa5ICm8lS/5tcMI69PSYuF+i4v'
    b'iGGXdS71fA8H5YSylvAAPpCldloZD8A9gJ/mh+Q7WtlS1X1q5G3XImWiBPCwbur7fDRa3ARA'
    b'g0YabL1zB9c6HiCshTNMDKSgOcrCeOs/0R9u9JewaTshtgAAAABJRU5ErkJggg==')

#----------------------------------------------------------------------
UseCase = PyEmbeddedImage(
    b'iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAQAAABKfvVzAAAAAmJLR0QA/4ePzL8AAAAJcEhZ'
    b'cwAALiMAAC4jAXilP3YAAAAHdElNRQfqBQ4XBALAP3vaAAAAJXRFWHRkYXRlOmNyZWF0ZQAy'
    b'MDI2LTA1LTE0VDIyOjU3OjMzKzAwOjAwvq7trwAAACV0RVh0ZGF0ZTptb2RpZnkAMjAyNi0w'
    b'NS0xNFQyMjoxNTo0MCswMDowMEDy5SgAAAAodEVYdGRhdGU6dGltZXN0YW1wADIwMjYtMDUt'
    b'MTRUMjM6MDQ6MDIrMDA6MDD36LZfAAAB8klEQVQ4y72TT0jTYRjHP8/79rMajqKY649phw6r'
    b'mwZp3YpyVMZOFWQjjR12SrAOQXjzPLBTF1GRgtUpMwqLOjYJtrqop1BM2CYR1HKx3/Z7Pew3'
    b'3do8dKjn9sLn88LzPN8H/nVJ9ePRNlC0kVAFW3jZDeT5if2nJDX4TjrooZs2moEcy8wxS5LC'
    b'liJVeBd3CQosyCJZoMUEOG7gNTHmKoq4uGaAEdklk+rxjvn+3CgwyIS3eMLpM7dMngeM40AU'
    b'cX+P8FCW1ODlty+NhYerwDPWsemWxAVn1LRxhzHAFU7yQmx9vZjwUMJHr9vgc76jWEefduJG'
    b'c4UkKECIcFBi+cReFAObOIToR9hD/oPEOEQEKQt+zsmKnvZgc7NuB2GKeNDT8pWztJQFH36W'
    b'rIxFuOHawjRhZVjmAL6y8FelgDXSHLX9BSYbIlMUKPhpJ81aWcjw3hwphX5jMdUA1/zCCZlW'
    b'3pGtjLWTGSmqa6WEB4dWzrvwLKso8ugzTtwoeklVekgybPY74zoYEJsVnrLAPHFWKXJMdNAZ'
    b'M/sYJgWgZ8pz/0yaS9zIHFbf1I++whO+cJtPXtOZve+MoLnHBAaiNeE7xRAXQRa3wmcCGF4R'
    b'42NV+KqUJjrooYv2zXgneEOqLt51B9TsHlBu2wOqk2oqyv+sDcAtqHuF6wRvAAAAAElFTkSu'
    b'QmCC')

