#----------------------------------------------------------------------
# This file was generated by /Users/humberto.a.sanchez.ii/PycharmProjects/code-ally-advanced/pyenv-3.13.9/lib/python3.13/site-packages/wx/tools/img2py.py
#
from wx.lib.embeddedimage import PyEmbeddedImage

embeddedImage = PyEmbeddedImage(
    b'iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAIAAACQkWg2AAAAA3NCSVQICAjb4U/gAAABhUlE'
    b'QVQokXWSvUtcQRTFf3fe0wWNbzG76SJKXI3pkypiZSGCgljY2RgQ/Qtiq3+BpYIIaUNIY0BU'
    b'yBbaqthI/GCjoAjK5i2G6EZ912Levg9ZD8NwhnvvuXPujFCDky9IxqMetFp5uDq2XAAn96Z5'
    b'bMnJdeI01C0A7s92/n2beiifCOBNbphXXSbbhkgoqYigmuyid79W/y4NuiZXkHyXeG2KoFE0'
    b'3msQt3vAtHa4kvFUGgONs5M1aYhkPGNjqgRBuEekpZHPHxl9FyZYCQNhkiUWLxqY6WVvktct'
    b'/DgIE2zUVdu9JpDNMP2BqfesHNK3TMlP3xNclECRmvbiEPkm+r+wf1l/vkbTHia+s3bE+jgL'
    b'Q7RnYz8pD5EnVco3zBXpmef3H7Y+sThMk5sYBhgUDZ4q+bfMFXk7z4nPYHdiSorL/0pkOnpd'
    b'S/wbZn+mHVSvjZaPg4tdVU1eLLni9znfVr/kAHq6SWsPLwuq8V+KvIXHi239OkK1InG7bAfP'
    b'fG+q11RKlj4C9qH2jViUX/QAAAAASUVORK5CYII=')

