#----------------------------------------------------------------------
# This file was generated by /Users/humberto.a.sanchez.ii/PycharmProjects/code-ally-advanced/pyenv-3.13.9/lib/python3.13/site-packages/wx/tools/img2py.py
#
from wx.lib.embeddedimage import PyEmbeddedImage

embeddedImage = PyEmbeddedImage(
    b'iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAIAAAAlC+aJAAAAA3NCSVQICAjb4U/gAAAGsUlE'
    b'QVRoge1aXWxURRT+5v7sTwulGhAJ7LahiU36INEoLXQLktIWH/BBjQRIVJSEaHww4gPVF5+K'
    b'xqgxPvliKBATQzTxJxgTSqFbUBpRjBhChP7xUyJYYqEFdrt3fLjbu7N3fu7c3dbEpF9umtm5'
    b'55w53zln5s7cXmAe8ygLJFgiuiBS324mV5v31RqxhdSw5tYjJ0vvTOTGh3KjA5k/e+i92wHu'
    b'Ke4Z1SviT+yONGwmkQpix2HaMCxCCABKQQgo5cyR/K1yZCilhE7T6Sy9M545c+hO+hNn4kpo'
    b'ArHGl2OtnSRaZcQXwYwoeIYloCNf6M9lcv+MTX3/1r3TnwstmII+w6zc/H4s9ZpR+YARr4Yh'
    b'ktGA64rfIU7GveU1/DLEJPFqu/5JYkWzQ2k+HgLnKp76MPLws8aCpbBiwRFSwhNwG7y81y8T'
    b'yI9r2VayCYY1ffFYAIHo6pdia18xFi6FGeUHc532GjwZYb9PPizy6qZl167J3biYu3a26C77'
    b'w1i0YuGrx4yqZcSuKGWouYczeX3ig1XOxJjXY7C3o+t3k2gVsSu8UHl1zBa0DzKZcvrZi5Ux'
    b'KpfE1r3Bjl4gQKIL7IbNJLZIxl5nAB1dYWn57LBzwycTadxJIpUCAtZDHcSugBlxHABwHDgO'
    b'KM3/1cyA7GJ1deyzMt5PV4DEqq26DSICiceJHdeMInvJIlpmpBXBMmubC257LVJdSw0beiUh'
    b'JMb+9PXLngkyXbV9c0m9d7eQASNWRQwLxZEOS0Y4cAnzBKJAeA1SudjTKmSAGqb6yVTCWs6W'
    b'ivBZIZNXZIwQwLAFBPIKEva+AcKiHDtqXcMvLlEOTCvfL1uFWJmm5Xi9EY8tC23Tg2Bz70ux'
    b'ZlrV/TxSCexJoSUJADmKtgP45ZpUV1iKfgJ5ZtwyJzSqs/LI+lMJdKaQShacMAnW1eD0mFiX'
    b'Bb8eWL57PjgOCCl6jvDEdOAKNyfQORN1FlkHvcMh7ASUkAzlnLZakoWC8eHoEN45jjPXQtsX'
    b'EPBKyN/JNNR1ydduKok9zVhXI3Z9bz8GrgaUJe9MiEkceJJSkGypUbne1Y9Tl4s6Szs8MQRE'
    b'k5hnzHIQyrhR70yJXe8Zwl7OdTUEPuhPYv1IuNBxXWaTXTDchs4iETCJ2aOqemK11Khc70oX'
    b'oq5ZKl6Dl5ESEE5ivwDnxNoE3m7Rcp01EvgMEY6bl5ER0IdrKKzr5SOfDaZHkAGdFMctHHwG'
    b'HXUi1wfRlcZPl8vabgToCgl4RnTW4+dXCbzvGUJXH05dCbHdCLtV4VHYjSqEfANTKpkp4Q/7'
    b'irOvNxaUc0CwnS5yVOLQgd/wwwW/YutKHH0R32zFmoT/TZvMofJRREB/gMkMnv4C7fvRN+K/'
    b'1boSPS/g661oXF4gr3PAZ0nK5Cl3HgjIgGwAt9E/ik0HxDQ2utnYhqYVKpsyyEqLhyADLHvI'
    b'X7h68ukRdOxHW7eKBpsNSILCXqVkQK2gmA8u+kfRsV+ajd4d+Ha7IBs6wVKjxDkggzobLA0X'
    b'YVchJYGgSOusTm4jPYL2bmzsRt+whMa2Iho8ZGNRZsvMEQgyBEkkZIP1j6BNRqNuhkZCtUjo'
    b'IAQB9Rxwwb/rTA/naRwX0Ti2A99txyMP6jrNi4UooXJI9s8UlZBG3048uix0sDgCYRA23fm5'
    b'MYz2bmzc5y8q20CraF+oMxazjIoUdCIhG0DW3+cW1b5CNnIOege1dHmEOA/IbJWwbaYUfcNo'
    b'24e1SaSSOD6Mn68KZIQ+BJ8HZMqaxPgoKhw6OYqTo35TmvZdhNgLhcVcl6IL5kCTy6of5FRy'
    b'egrkgNn+/4AznRUQwL0JSun/4/8Dd296d5lV6OYQnGmZsmZadcpmFmzeOO95yJTQ2AByWdjS'
    b'1UCd1sCVRwgdm6wP+W3ypROeBSYDgz3O5HjgAUIaFe2LdYiFziGGUiA7RQePCAggcxvnDhEn'
    b'Q0s6D/Dg90Wl2fERoGc+Q3bS6yn6WoXeOEcankOsOoTJ/xZketL5cgsyt7ye4s9tMrfo1HVS'
    b't4katvqVus6L3tkCOy49vAujafYu98HTX7/DjJHEGkpMn6PCksDsTehgOwMf0ZPv+bREn5ON'
    b'9sGwsLwJc/2BYjF8x2J/egc+pkfeBPdKTfg9HMVIL8YvkJr11Kqc9bIJzJLXyI+VnaSHd+HH'
    b'd3nvZQQAANfP4o+DBBSLG4gd85UNCxmxQHlZKRZSkZ3Cr5/Sr7bgUtpvxbMmJeDBrkTNBiSa'
    b'cX894oth2a4anVGmMz9nB7ks7t7E3+dx6QSGj7Ar5jzmMRf4F0a7vEjCzWz8AAAAAElFTkSu'
    b'QmCC')

