#----------------------------------------------------------------------
# This file was generated by /Users/humberto.a.sanchez.ii/PycharmProjects/code-ally-advanced/pyenv-3.13.9/lib/python3.13/site-packages/wx/tools/img2py.py
#
from wx.lib.embeddedimage import PyEmbeddedImage

embeddedImage = PyEmbeddedImage(
    b'iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAIAAAAlC+aJAAAAA3NCSVQICAjb4U/gAAAHQElE'
    b'QVRoge1aSW8URxT+qrsHr3gGY7CcADHYDlI4ICyIQMgYA8pyQIqiJFyjJBJCyiEKCWATvAUI'
    b'BCmLcuKSU5QL/yBeMeIQkKxEQSJgGyPCbsAw9nib6a4ceqa6uruquntsKzn4aTSqrn716vvq'
    b'vap6VTPAkizJvIQEapQa+huryl8vj1cXFS03dIMEN5mPpClNps3Rqakrz5M9Y88mM6ZaX4Vm'
    b'TVHB4dpX9ldWFOt6ka7HNGKQHHxKQQgo9dkj2Vfz0KFABkib1rNM5sK9Rz+N/nNvejYygY/X'
    b'vdT8anWZoccNY5mmKXhGJhBGP1c/Z1kPZmZbro/8eveh0IAuqCLk3Ka6T9evXV0QS8Riet4x'
    b'Y0NxAxLo2K9Ywa2jE5KIGW+vXlmga5eePvcPhoDAd5vq3qtaVVkQK9S0wBEK4MAU7IJfn9XL'
    b'FABQGtO07Ykyg2j9T8cDCHy0rupQ9cuVhQUF/rBhoFnBT0ZY79GPKoSAUkPTdpTHR1LT1yZS'
    b'rpf8w5rCgv6d9VUFy4p1gWf+DzI2l97c//uD2TlW4xrmwzVry3S9WNedoWJxzAe0R2Q686nn'
    b'P5zOqmWxz2vW8Z07BEoNfX9lRdyQj32IDkK1FYaWxw4/N9w6n6ytKuFAOgTerFhRrOvLNA2W'
    b'BQCWBcsCpdnvkB6Qffi2YezzOuwRAKWJmNG0MiEgsC1RVqRe72VAZSM6v5FWDNbORJxVGKxU'
    b'XVwYI1A1DiTGP3rqZXuCrK3S/sblxeylM+RlLM8JM3EjEctjnkA0ELlCRSzGGjke0GlQZpfH'
    b'Ws6HinCvkOkrPEZIjANquNtLfKp2cXgm+dlRtg3K0hZhLV8Im2oCYQzZbt1Qi3cPYH2NeOWB'
    b'JLdhsqEW77yPDbXRVy3HhieEcuQCY9dG/8N5GAZME+dOYqDXRRIQFPjHXXvw5VfQdWQy+Owg'
    b'bg1HWZGcCt4DogaKTWdzPQwDAHQdR05g1x5Bc2/HubYNTThyAnbGZRjYXK9q67fDQQ19UoFv'
    b'0/lzEGbuvKdpOHICDU1cH/L0oaEJR1vBNk3TxB+DYedSNgScGHITiDT5Robw7dfOJq9pONqK'
    b'hiZx7LJHD3rLwrmTuDUksK9aZ9UeCG/oYg/Odgo4yNru2uNFf7YT/d0RViSfcJOYX6Fkk0/I'
    b'AXBg2Rzsek/bxr0C9HZztfgxUKEHhCTDjITQD417XTp+9Gc60N/tsinLQJViBLznl3MqSQEI'
    b'yULx+IFSDPSCUjH6gV7V0RTcHuLXkRJwb3ICUewPdigfa3M4HGvLKrNKhp6PnPDhKtIJ8oCa'
    b'iceuDYvn0NwOUBA5+jz6dTtB5IEwVymycLL90Nye5UCIs2ZbFr5px8Weed3e+a5z3KsQX1Bv'
    b'6YrO7JyipcOVCNEceo99RaoSDgNPIACnwLS/A6cn6r6zkWR1lgVCsguOXQj0vJuPaA6Ecasn'
    b'2eQLjXvR3O7EPatvbgeA/u6wt3rhJCgblYmM5O59zgQAQC0gl1pn5zTHgZniC2Hm2wKcB4Qk'
    b'PegtC6fbcbrNtcc1t2P3vuABCr2pBa1CkF64ekdFgL4tm1BQipYO19pKqTOhI61Cue6FBCJe'
    b'xHrQM4jgVkwbil3gObR0AL75ELJft+Q7B3jxoz/dlk0umNiPfg59XdJVCL7oDSBAveflrFH1'
    b'CAnR93UJuurrAqU43uniwGLJI2pvREgl1COxe58DyEZ/qjW7GUP0I4jtB57D8U6nPuoGCiDa'
    b'tQp1n9Rq6rxjb6OH8q6zvxunWl3rUksHaupUmZwQj4CAH6Xa6JatYL+D2OjtIAls29fl4qDr'
    b'2LI1YLDkxKIc6nmhFINXkckAgGlm0av1GTjGwb4TyGQweDVCWzcZSTIXuDYDGBnCoQ9Rvw2D'
    b'VzEyFLCD+ut7f8Od29iyNds8ZFufRDkP+Adg+CaGb+aTftuF4ZtZ5godP4bg84CscUhi/tRD'
    b'DWh+Ovleq4SRqJNS1m/IOZC28s1AAzlggX8f4KE6BJKmSf0hlNfmIkWWnx1f23F79QPAh9Do'
    b'zGzGbzeqW8OEzbxt3kjNMICOB65MpNJMNe8DR9TsMoxNHgMhoPTyxCQz4HigZzz5bG4u7K2Y'
    b'bKTDfHhAvIQ5xFA6ZVnd40kBgUnTuvDk+RzPPg8QvLBzsycvimrHTeDnh09SpsPN9ceC69Mz'
    b'H6xckVD82+C/lpRFD1y/NSEjMGFaY5n0W+XxGEQnSVmsL7Zw/R4cvnMpOcm/9A72X6mZQkJ2'
    b'xEuzL4RXKZ5j50JN6CA7398fO3v3kaeRIFoGkimDYPvyksX+g6JXZHdNAIAf7z/+YvS+fwAE'
    b'BCjQ92JyeGa2MV5aopGFD5tAL7ECIQBSpnVw5M6Zu4+F7pPO12tTM7+MjVNCXispdP15zh8G'
    b'MmKB+rJQzLliyrLOP3xy4O/bl5IprxFmTPaCSYmuNZWV7iwr2VhUWBHTY8zRkeI7tKQpHc+Y'
    b'N6ZnLydT3S8m+BVzSZZkMeRfKfKqvGRYJkwAAAAASUVORK5CYII=')

