#----------------------------------------------------------------------
# This file was generated by /Users/humberto.a.sanchez.ii/PycharmProjects/code-ally-advanced/pyenv-3.13.9/lib/python3.13/site-packages/wx/tools/img2py.py
#
from wx.lib.embeddedimage import PyEmbeddedImage

embeddedImage = PyEmbeddedImage(
    b'iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAIAAACQkWg2AAAAA3NCSVQICAjb4U/gAAABqElE'
    b'QVQokW2Sv2sUURDHP2/35e52T46YRPSQQNALKCGXWPofiKmEdKZJpyAWVoKIigh2dpJGUnit'
    b'2KawtBJc9wRR0RhExVwKYb2Ll9vsvbHYn3fkMcW8me+8+c68ryI9japbm9AcdYLDaHv/X+wr'
    b'4IzrPFs+f7bqTFjWkQXAu6B7vf3pe/9AAa8uLs9X3VmnorK8CEohkgdga+/P5Tdt3ag6864z'
    b'WymrQjqBFiIKLp04PudWdE3rEihjxkkU69OamtYWIokZgwhT09h2ftWa6ZkcI2IBGEPcwRjq'
    b'p2m9ZKEJsNDk+QtO1hOAMYBdL5eunpo5Fr8KdH7z+QN3HxGG3LjFwzu89zNWGz93LUj5ZOZ7'
    b'tDa5dpPWJr43kkIshJEZjGFxibV1nj5hbZ3FpTwlgqCThcQGNC9w/zH3btP2+PqFB6mfLk2P'
    b'DC3Crx+srnAYAvhvWV1hcrK4Yh1EUd5BKTq7QPLNShEO2Otk6G4UWdv9gd/dl8Kmxy2dzfvb'
    b'2zkIbeB10DtXKTecgjoyaaSO1+tf+fgtGA5zvc2VSzVtjwskYTLcGYSx/x+1tgBDIYZlWgAA'
    b'AABJRU5ErkJggg==')

