#----------------------------------------------------------------------
# This file was generated by /Users/humberto.a.sanchez.ii/PycharmProjects/code-ally-advanced/pyenv-3.13.9/lib/python3.13/site-packages/wx/tools/img2py.py
#
from wx.lib.embeddedimage import PyEmbeddedImage

embeddedImage = PyEmbeddedImage(
    b'iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAIAAACQkWg2AAAAA3NCSVQICAjb4U/gAAABeklE'
    b'QVQokXWSu0oDURCGv3N2Ywp1Q4x2BjQmMc8gYmXhtdDGR4g+gehLiIUWQhBsLMRGBC0sbbTw'
    b'ho1gEAXFQoJLRFwvZyx2k+zG+DMcZs6cmf/wzyhqsLqzKu7QCuK5Py9l31eAlcq0z5Ws1ABW'
    b'rGUB8P14/r678FO5V4BTPNI9OZ1Io1TQUlAKkTCLfN0cvpUmbJ3Kqu6cctKCQurZxlmDsvNj'
    b'Otlnq7gjqs1I43W4Jgql4o72cyIYgwizBRaH6GwLwiYDNGAMxuA7B7ekHa6KLA3TEQtSdQO0'
    b'RBmqH8zvM7JJr8P1AkvDJOIhEtAIRpo7lSsU9xjdYjTDxnSEwfYZkIiU/UmWR5jMs37K2inG'
    b'1AXHJlQAtMdYGWdqkLUTCqu4XlRosBHEICa4nchz/8rgKu5Hq4ELNp9u+Evbl77gQdgMr6ql'
    b'UjbPFyLyV/WwesZgns7k9c4C5OGYZIGurEhjl+oDDcLnM9mZwXNDrIk+/llvvCrune/+Al+8'
    b'8GU8vhp5AAAAAElFTkSuQmCC')

