#----------------------------------------------------------------------
# This file was generated by /Users/humberto.a.sanchez.ii/PycharmProjects/code-ally-advanced/pyenv-3.13.9/lib/python3.13/site-packages/wx/tools/img2py.py
#
from wx.lib.embeddedimage import PyEmbeddedImage

embeddedImage = PyEmbeddedImage(
    b'iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAIAAAAlC+aJAAAAA3NCSVQICAjb4U/gAAAGtklE'
    b'QVRoge1aXWxURRT+5v7sTwulGhDB7tKAsUkf/IvQYgsFl4g+8PNgILTEBzEhGh+M+CLoExg1'
    b'Ro3xyQdNQAMSgm9tMaHadkHpJgYSMYQI9IdtagRLLLTAbveOD7u9Ozt3Zu7c3dbEpF82m7tz'
    b'zzlzvnPO/NzZC8xjHhWB+EuEF4Qanjfja8wH6o3IQmpYc+uRk6V3J3Ljg7mRVOaPHnr/jo97'
    b'intGbV10w75Q4xYSqiJ2FKYNwyKEAKAUhIBSjzlSuFWJDKWU0Gk6naV3xzMXTtxNfuFMjAYm'
    b'EGnaE0m8Q8I1RnQRzJCCZ1ACOvLF9lwm98/YVPf++78eFVowBW2GWb3l40jrG0b1Q0a0FoZI'
    b'RgN5V3iHPDL5W+4FL0NMEq21G14kVjg7mPTGQ+Bc1dZPQ4+/ZCxYCiviHyElXIH8hVfebZcJ'
    b'FPq1bCveDMOavtrrQyC85pXIs68ZC5fCDHs7yzvtXnjJCNs5+aAoqJuWXb82d/Nq7s+LJXfZ'
    b'H8aiuoWv9xo1y4hdVU5Xcw9n8sbEJ084E2Nui8HeDrftI+EaYle5oXLrmC1oDjKZStrZDytj'
    b'VC+JrH+L7b1IgIQX2I1bSGSRjL1OBzq6wtLi7LBjg5MJNb1KQtUCAtZjm4ldBTPkOADgOHAc'
    b'UFr41syA7MPq6thnZdyfeQESqbVWbRQRiK0mdlQziuxHFtEKI60IllnfUnTbvSK19dSwoVcS'
    b'QmLsT65dtibIdNX2zSUN7t1iBoxIDTEslEY6KBlhx2WME4gC4V6Q6sWuVjED1DDVK1MZczlb'
    b'KsK1QiavyBghgGELCBQUJOy5DoKiEjtqXYMXlyh7raxejjebsGa5wLp6FtIvFYVNF4LNPZdi'
    b'YTaeWY5THTAJAJwZwQdncWYECL4bVZeK1wfvHsxgbamnOTCbrXXxgvcAWuPo3IXOXWiNBY6u'
    b'kIyOjJiAF7JF56chZJ0SydY4OtsLNMpzTgcqAr5gs3F+DJu+wY+DvAxLg3VatqjpjBP2oyoh'
    b'oYLMKIDzY9h+XEmjHS0xgS5LBkxZVlpCXiEdQwNpbD+OxBEBjXVxdLWjsx2t8ZJ2nb2Qfskx'
    b'BIKkkpNJjWLbd0gcQY+cRkuszDHg9QH6gzjQ4EuNYrucRncHujrQGpfalO1A1fAZxLLdoiwb'
    b'OjS6d6Ml5rN7hfbY8BnEMkd9iQ2kse0YEofFNE7tRtfMEA9ariipoCDTKEdVERUXA6NyGitw'
    b'aje6O/ghrtUv0yLIACRRkbX7ZmxgFFuPInEYPdfENE7uQNTSmr4LCRcScGkFGriQbzc4O+fS'
    b'2HpMTGPzo3j5SZWuwgfmecDPUdaWMEhcu+bhF6voOD6HaN4S8t+NumANccGWncCxEV0bw/51'
    b'SKwUeP/DFRy5oMXTC58HGhlkJIVorsOB9WLX+4fxfj+Sw6U++G3L2WufDAR9APe6vn89Num5'
    b'ziJfS/m1LH8hK0VBBrjalR64KstM7fqhvsIDkE656magoKB9ECsTaK7DgTaV62zUgz7BeVHm'
    b'GBAikOt5yEpFv1wZAp6NHrT/Mmqqw7sy14dwUB51GXyyoR7EnCEoI9FUh/fasGmVQLd/CAd7'
    b'kRzRtVnGJAEdArKoP/UwDibkrvehf0g8m8nsl5cZnxKCJBJPL0PfHtierWA+6v0zBSPU5ZyQ'
    b'ZcCFmliZf/o+t5L3nnOdQ3nloaPLTKMz/zfpzM29g8jRwtFQ3xAO9aJviJdRLIiB5v5ZywAb'
    b'iVQaG75CWz2SwziXDuy0e6Ejw/lAiHwzF2gdGEhjIM3T8174OlShTJnHKjpg7VDJw4pOv2p/'
    b'mDGQy6q37mUs9TqlIpRnffXqOtNZAQHcn6CU/j/+H7h3y73LPFLeGoQzLVPWTKtO2cyCzZuX'
    b'XQ+ZEhpLIZeFrbXQVDJdCgOk1uVKkV4/61pgMnCtx5kc1zwVk0Va58M6xELnZI5SIDtFr50W'
    b'EEDmDi6dIE7GZV+GEyzKONXzBaWgF75GdtJtKXlbhd68RBp3IFIbwOR/CzI96Zzcicxtt6X0'
    b'dZvMbTp1g6x6gRp25TvH2QLbL+3ai5Eke9fzwtNfv8GMkNhaSkzOUWFJYPYGtL+d1Gf05484'
    b'LdHrZCP9MCw80oy5fkGxFLIzpQJSn9PTb3u3+8L34SiGf8L4FbKijVrVs142vllyLwp9ZSdp'
    b'11788qHgYUVCAABw4yJ+/5aAYnEjsSNc2bDQedoSystKsZiK7BTOf0m/34nrSd6Ka01KwIVd'
    b'jRUbEWvBgw2ILoZl59WKzw8zP2cHuSzu3cLfl3H9LIZOszPmPOYxF/gX24ZzByqPCQQAAAAA'
    b'SUVORK5CYII=')

